/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.3 RC4.glb --t
*/

import * as THREE from 'three'
import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    ROOF: THREE.Mesh
  }
  materials: {
    ['Black.003']: THREE.MeshStandardMaterial
  }
}

export function RoofModel40(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/models/others/RC4.glb') as GLTFResult
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.ROOF.geometry} material={materials['Black.003']} position={[-0.012, 3.444, -1.746]} scale={[0.012, 0.015, 0.019]} />
    </group>
  )
}

useGLTF.preload('/models/others/RC4.glb')
