/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.11 ./public/models/others/Top Roof Carrier.glb --t
*/

import * as THREE from 'three'
import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    ROOF: THREE.Mesh
  }
  materials: {
    ['Black.001']: THREE.MeshStandardMaterial
  }
}

export function RoofModel(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/models/others/Top Roof Carrier.glb') as GLTFResult
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.ROOF.geometry} material={materials['Black.001']} position={[-0.01, 3.35, -1.36]} scale={[0.01, 0.01, 0.02]} />
    </group>
  )
}

useGLTF.preload('/models/others/Top Roof Carrier.glb')
