/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.3 public/models/rims/fs/Rim 1.glb --t
*/

import * as THREE from 'three'
import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    ['Cylinder1_extract2007_1-mesh001']: THREE.Mesh
    ['Cylinder1_extract2007_1-mesh001_1']: THREE.Mesh
  }
  materials: {
    ['default #1']: THREE.MeshStandardMaterial
    ['Steel.003']: THREE.MeshStandardMaterial
  }
}

export function FSRim1(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/models/rims/fs/Rim 1.glb') as GLTFResult
  return (
    <group {...props} dispose={null}>
      <group position={[-0.013, 0.534, 0.496]} rotation={[1.196, -1.565, -1.571]} scale={[0.327, 0.327, 0.331]}>
        <mesh geometry={nodes['Cylinder1_extract2007_1-mesh001'].geometry} material={materials['default #1']} />
        <mesh geometry={nodes['Cylinder1_extract2007_1-mesh001_1'].geometry} material={materials['Steel.003']} />
      </group>
    </group>
  )
}

useGLTF.preload('/models/rims/fs/Rim 1.glb')
