/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.3 public/models/rims/fs/Rim 10.glb --t
*/

import * as THREE from 'three'
import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    Nut007: THREE.Mesh
    Nut007_1: THREE.Mesh
    Nut007_2: THREE.Mesh
  }
  materials: {
    ['Steel.010']: THREE.MeshStandardMaterial
    ['Blue paint new.001']: THREE.MeshStandardMaterial
    ['Black Metal Paint.001']: THREE.MeshStandardMaterial
  }
}

export function FSRim10(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/models/rims/fs/Rim 10.glb') as GLTFResult
  return (
    <group {...props} dispose={null}>
      <group position={[1.24, 0.52, 0.493]} rotation={[Math.PI, 0, Math.PI]} scale={2.716}>
        <mesh geometry={nodes.Nut007.geometry} material={materials['Steel.010']} />
        <mesh geometry={nodes.Nut007_1.geometry} material={materials['Blue paint new.001']} />
        <mesh geometry={nodes.Nut007_2.geometry} material={materials['Black Metal Paint.001']} />
      </group>
    </group>
  )
}

useGLTF.preload('/models/rims/fs/Rim 10.glb')
