/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.3 public/models/rims/fs/Rim 5.glb --t
*/

import * as THREE from 'three'
import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    ['Circle006-mesh002']: THREE.Mesh
    ['Circle006-mesh002_1']: THREE.Mesh
  }
  materials: {
    ['default #1.002']: THREE.MeshStandardMaterial
    ['Steel.006']: THREE.MeshStandardMaterial
  }
}

export function FSRim5(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/models/rims/fs/Rim 5.glb') as GLTFResult
  return (
    <group {...props} dispose={null}>
      <group position={[0, 0.53, 0.478]} rotation={[-3.11, 0, Math.PI / 2]} scale={[-0.397, -0.452, -0.397]}>
        <mesh geometry={nodes['Circle006-mesh002'].geometry} material={materials['default #1.002']} />
        <mesh geometry={nodes['Circle006-mesh002_1'].geometry} material={materials['Steel.006']} />
      </group>
    </group>
  )
}

useGLTF.preload('/models/rims/fs/Rim 5.glb')
