/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.3 public/models/rims/fs/Rim 6.glb --t
*/

import * as THREE from 'three'
import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    rIM_6: THREE.Mesh
  }
  materials: {
    ['default  #2']: THREE.MeshStandardMaterial
  }
}

export function FSRim6(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/models/rims/fs/Rim 6.glb') as GLTFResult
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.rIM_6.geometry} material={materials['default  #2']} position={[-1.274, 0.525, 1.434]} rotation={[-Math.PI, 0, -Math.PI]} scale={[0.489, 1.061, 1.061]} />
    </group>
  )
}

useGLTF.preload('/models/rims/fs/Rim 6.glb')
