/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.4 public/models/rims/Rim 10.glb --t
*/

import * as THREE from 'three'
import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    Nut001: THREE.Mesh
    Nut001_1: THREE.Mesh
    Nut001_2: THREE.Mesh
  }
  materials: {
    ['Steel.001']: THREE.MeshStandardMaterial
    ['Blue paint new']: THREE.MeshStandardMaterial
    ['Black Metal Paint']: THREE.MeshStandardMaterial
  }
}

export function RimModel10(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/models/rim//Rim 10.glb') as GLTFResult
  return (
    <group {...props} dispose={null}>
      <group position={[1.24, 0.52, 1.429]} rotation={[Math.PI, 0, Math.PI]} scale={2.716}>
        <mesh geometry={nodes.Nut001.geometry} material={materials['Steel.001']} />
        <mesh geometry={nodes.Nut001_1.geometry} material={materials['Blue paint new']} />
        <mesh geometry={nodes.Nut001_2.geometry} material={materials['Black Metal Paint']} />
      </group>
    </group>
  )
}

useGLTF.preload('/models/rim//Rim 10.glb')
