/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.11 ./public/models/rims/Rim 1.glb --t
*/

import * as THREE from 'three'
import React, { useRef } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    ['rims-1']: THREE.Mesh
  }
  materials: {}
}

type ActionName = 'rims-1'
type GLTFActions = Record<ActionName, THREE.AnimationAction>

export function RimModel1(props: JSX.IntrinsicElements['group']) {
  const group = useRef<THREE.Group>(null)
  const { nodes, materials, animations } = useGLTF('/models/rims/Rim 1.glb') as GLTFResult
  const { actions } = useAnimations<any>(animations, group)
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <mesh name="rims-1" geometry={nodes['rims-1'].geometry} material={nodes['rims-1'].material} position={[1, 0.52, -2.53]} rotation={[1.2, -1.57, -1.57]} scale={0.33} />
      </group>
    </group>
  )
}

useGLTF.preload('/models/rims/Rim 1.glb')
