/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.4 public/models/rims/Rim 2.glb --t
*/

import * as THREE from 'three'
import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    ['Felge003_4-mesh']: THREE.Mesh
    ['Felge003_4-mesh_1']: THREE.Mesh
  }
  materials: {
    ['default']: THREE.MeshStandardMaterial
    ['Steel.001']: THREE.MeshStandardMaterial
  }
}

export function RimModel2(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/models/rims/Rim 2.glb') as GLTFResult
  return (
    <group {...props} dispose={null}>
      <group position={[-1.182, 0.52, 1.431]} scale={[0.527, 1.237, 1.237]}>
        <mesh geometry={nodes['Felge003_4-mesh'].geometry} material={materials['default']} />
        <mesh geometry={nodes['Felge003_4-mesh_1'].geometry} material={materials['Steel.001']} />
      </group>
    </group>
  )
}

useGLTF.preload('/models/rims/Rim 2.glb')
