/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.4 public/models/rims/Rim 3.glb --t
*/

import * as THREE from 'three'
import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    ['Circle016_4-mesh']: THREE.Mesh
    ['Circle016_4-mesh_1']: THREE.Mesh
    ['Circle016_4-mesh_2']: THREE.Mesh
    ['Circle016_4-mesh_3']: THREE.Mesh
  }
  materials: {
    ['10_Front Whell.003']: THREE.MeshStandardMaterial
    ['10_Front Whell']: THREE.MeshStandardMaterial
    ['10_Front Whell.001']: THREE.MeshStandardMaterial
    ['10_Front Whell.002']: THREE.MeshStandardMaterial
  }
}

export function RimModel3(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/models/rims/Rim 3.glb') as GLTFResult
  return (
    <group {...props} dispose={null}>
      <group position={[-1.192, 0.522, 1.427]} scale={[0.706, 1.378, 1.378]}>
        <mesh geometry={nodes['Circle016_4-mesh'].geometry} material={materials['10_Front Whell.003']} />
        <mesh geometry={nodes['Circle016_4-mesh_1'].geometry} material={materials['10_Front Whell']} />
        <mesh geometry={nodes['Circle016_4-mesh_2'].geometry} material={materials['10_Front Whell.001']} />
        <mesh geometry={nodes['Circle016_4-mesh_3'].geometry} material={materials['10_Front Whell.002']} />
      </group>
    </group>
  )
}

useGLTF.preload('/models/rims/Rim 3.glb')
