/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.4 public/models/rims/Rim 4.glb --t
*/

import * as THREE from 'three'
import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    ['Circle014_2-mesh']: THREE.Mesh
    ['Circle014_2-mesh_1']: THREE.Mesh
  }
  materials: {
    ['default.001']: THREE.MeshStandardMaterial
    ['Steel.001']: THREE.MeshStandardMaterial
  }
}

export function RimModel4(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/models/rim/Rim 4.glb') as GLTFResult
  return (
    <group {...props} dispose={null}>
      <group position={[-1.133, 0.517, 1.427]} scale={0.952}>
        <mesh geometry={nodes['Circle014_2-mesh'].geometry} material={materials['default.001']} />
        <mesh geometry={nodes['Circle014_2-mesh_1'].geometry} material={materials['Steel.001']} />
      </group>
    </group>
  )
}

useGLTF.preload('/models/rim/Rim 4.glb')
