/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.4 public/models/rims/Rim 5.glb --t
*/

import * as THREE from 'three'
import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    ['Circle006-mesh001']: THREE.Mesh
    ['Circle006-mesh001_1']: THREE.Mesh
  }
  materials: {
    ['default #1.002']: THREE.MeshStandardMaterial
    ['Steel.003']: THREE.MeshStandardMaterial
  }
}

export function RimModel5(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/models/rim/Rim 5.glb') as GLTFResult
  return (
    <group {...props} dispose={null}>
      <group position={[0, 0.53, -0.542]} rotation={[-3.11, 0, Math.PI / 2]} scale={[-0.397, -0.452, -0.397]}>
        <mesh geometry={nodes['Circle006-mesh001'].geometry} material={materials['default #1.002']} />
        <mesh geometry={nodes['Circle006-mesh001_1'].geometry} material={materials['Steel.003']} />
      </group>
    </group>
  )
}

useGLTF.preload('/models/rim/Rim 5.glb')
