/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.4 public/models/rims/Rim 7.glb --t
*/

import * as THREE from 'three'
import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    ['Plane057_1-mesh']: THREE.Mesh
    ['Plane057_1-mesh_1']: THREE.Mesh
    ['Plane057_1-mesh_2']: THREE.Mesh
    ['Plane057_1-mesh_3']: THREE.Mesh
    ['Plane057_1-mesh_4']: THREE.Mesh
  }
  materials: {
    ['Anodized Aluminum Brushed 90° Black #1.001']: THREE.MeshStandardMaterial
    ['Anodized Aluminum Brushed 90° Black #1']: THREE.MeshStandardMaterial
    ['Anodized Aluminum Brushed 90° Black #1.002']: THREE.MeshStandardMaterial
    ['Anodized Aluminum Brushed 90° Black #1.003']: THREE.MeshStandardMaterial
    ['Steel.001']: THREE.MeshStandardMaterial
  }
}

export function RimModel7(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/models/rims/Rim 7.glb') as GLTFResult
  return (
    <group {...props} dispose={null}>
      <group position={[0.003, -0.01, 1.344]}>
        <mesh geometry={nodes['Plane057_1-mesh'].geometry} material={materials['Anodized Aluminum Brushed 90° Black #1.001']} />
        <mesh geometry={nodes['Plane057_1-mesh_1'].geometry} material={materials['Anodized Aluminum Brushed 90° Black #1']} />
        <mesh geometry={nodes['Plane057_1-mesh_2'].geometry} material={materials['Anodized Aluminum Brushed 90° Black #1.002']} />
        <mesh geometry={nodes['Plane057_1-mesh_3'].geometry} material={materials['Anodized Aluminum Brushed 90° Black #1.003']} />
        <mesh geometry={nodes['Plane057_1-mesh_4'].geometry} material={materials['Steel.001']} />
      </group>
    </group>
  )
}

useGLTF.preload('/models/rims/Rim 7.glb')
