/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.11 ./public/models/rims/Rim 7.glb --t
*/

import * as THREE from 'three'
import React, { useRef } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    ['rims-7001']: THREE.Mesh
  }
  materials: {
    ['Rough Iron Steel.002']: THREE.MeshStandardMaterial
  }
}

type ActionName = 'rims-7.001'
type GLTFActions = Record<ActionName, THREE.AnimationAction>

export function RimModel7(props: JSX.IntrinsicElements['group']) {
  const group = useRef<THREE.Group>(null)
  const { nodes, materials, animations } = useGLTF('/models/rims/Rim 7.glb') as GLTFResult
  const { actions } = useAnimations<any>(animations, group)
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <mesh name="rims-7001" geometry={nodes['rims-7001'].geometry} material={materials['Rough Iron Steel.002']} position={[0, -0.01, 1.35]} />
      </group>
    </group>
  )
}

useGLTF.preload('/models/rims/Rim 7.glb')
