/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.11 ./public/models/others/basket.glb --t
*/

import * as THREE from 'three'
import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    Plane: THREE.Mesh
    basket: THREE.Mesh
  }
  materials: {
    ['Black Plastic.001']: THREE.MeshStandardMaterial
  }
}

export function BasketModel(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/models/others/basket.glb') as GLTFResult
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Plane.geometry} material={materials['Black Plastic.001']} position={[0.04, 1.94, -2.44]} />
      <mesh geometry={nodes.basket.geometry} material={materials['Black Plastic.001']} position={[0.02, 2.17, -2.07]} rotation={[Math.PI, 0, Math.PI]} scale={[0.09, 0.08, 0.09]} />
    </group>
  )
}

useGLTF.preload('/models/others/basket.glb')
