/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.3 garage/scene.gltf --t
Author: jimbogies (https://sketchfab.com/jimbogies)
License: SKETCHFAB Standard (https://sketchfab.com/licenses)
Source: https://sketchfab.com/3d-models/large-empty-warehouse-or-showroom-b188e4872c264049b519e5193a7c7521
Title: Large Empty Warehouse or Showroom
*/

import * as THREE from 'three'
import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'
import { Model } from './Kart6'

type GLTFResult = GLTF & {
  nodes: {
    Object_2: THREE.Mesh
  }
  materials: {
    material: THREE.MeshStandardMaterial
  }
}

export function GarageModel(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/models/garage/scene.gltf') as GLTFResult
  return (
    <group {...props} dispose={null}>
      <mesh  scale={[10,10,10]} geometry={nodes.Object_2.geometry} material={materials.material} rotation={[-Math.PI / 2, 0, 0]} />
      <Model/>
    </group>
  )
}

useGLTF.preload('/models/garage/scene.gltf')
