/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.3 Kart_Four_Seater.glb --t
*/

import * as THREE from 'three'
import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'
import { Feature4 } from './Feature'

type GLTFResult = GLTF & {
  nodes: {
    Object_0_1: THREE.Mesh
    Object_0_2: THREE.Mesh
    Cylinder019: THREE.Mesh
    Cylinder020: THREE.Mesh
    Cube015: THREE.Mesh
    Cube016: THREE.Mesh
    Cube003: THREE.Mesh
    Cube004: THREE.Mesh
    Cube005: THREE.Mesh
    Cube006: THREE.Mesh
    Cube001: THREE.Mesh
    Cube002: THREE.Mesh
    Cube007: THREE.Mesh
    Cube008: THREE.Mesh
    Cube009: THREE.Mesh
    Cube010: THREE.Mesh
    Plane001: THREE.Mesh
    Plane052: THREE.Mesh
    Cube019: THREE.Mesh
    Cube020: THREE.Mesh
    Cube022: THREE.Mesh
    Cylinder014: THREE.Mesh
    Cylinder015: THREE.Mesh
    Cylinder017: THREE.Mesh
    Plane049: THREE.Mesh
    Plane053: THREE.Mesh
    hub_rf001: THREE.Mesh
    hub_rf002: THREE.Mesh
    hub_rf003: THREE.Mesh
    hub_rf006: THREE.Mesh
    hub_rf007: THREE.Mesh
    hub_rf008: THREE.Mesh
    hub_rf010: THREE.Mesh
    hub_rf011: THREE.Mesh
    hub_rf012: THREE.Mesh
    hub_rf014: THREE.Mesh
    hub_rf015: THREE.Mesh
    hub_rf016: THREE.Mesh
    Mesh001: THREE.Mesh
    Mesh002: THREE.Mesh
    Mesh003: THREE.Mesh
    Mesh004: THREE.Mesh
    Mesh005: THREE.Mesh
    Mesh006: THREE.Mesh
    Mesh007: THREE.Mesh
    Mesh008: THREE.Mesh
    Mesh009: THREE.Mesh
    Mesh010: THREE.Mesh
    Mesh011: THREE.Mesh
    Mesh012: THREE.Mesh
    suspension_rf001: THREE.Mesh
    suspension_rf002: THREE.Mesh
    suspension_rf003: THREE.Mesh
    suspension_rf006: THREE.Mesh
    suspension_rf008: THREE.Mesh
    suspension_rf009: THREE.Mesh
    suspension_rf011: THREE.Mesh
    suspension_rf012: THREE.Mesh
    Bolt006: THREE.Mesh
    Bolt008: THREE.Mesh
    Bolt009: THREE.Mesh
    Bolt010: THREE.Mesh
    Bolt011: THREE.Mesh
    Bolt012: THREE.Mesh
    Bolt013: THREE.Mesh
    Circle: THREE.Mesh
    Circle006: THREE.Mesh
    Circle011: THREE.Mesh
    Circle012: THREE.Mesh
    Circle013: THREE.Mesh
    Circle014: THREE.Mesh
    Circle015: THREE.Mesh
    Circle016: THREE.Mesh
    Circle017: THREE.Mesh
    Circle018: THREE.Mesh
    Circle019: THREE.Mesh
    Circle020: THREE.Mesh
    Cube011: THREE.Mesh
    Cube012: THREE.Mesh
    Cube013: THREE.Mesh
    Cube017: THREE.Mesh
    Cube018: THREE.Mesh
    Cube025: THREE.Mesh
    Cube026: THREE.Mesh
    Cube027: THREE.Mesh
    Cube028: THREE.Mesh
    Cube031: THREE.Mesh
    Cube032: THREE.Mesh
    Cube033: THREE.Mesh
    Cube034: THREE.Mesh
    Cube036: THREE.Mesh
    Cube037: THREE.Mesh
    Cube038: THREE.Mesh
    Cube040: THREE.Mesh
    Cube041: THREE.Mesh
    Cube042: THREE.Mesh
    Cube043: THREE.Mesh
    Cube046: THREE.Mesh
    Cube047: THREE.Mesh
    Cube051: THREE.Mesh
    Cube052: THREE.Mesh
    Cube053: THREE.Mesh
    Cube057: THREE.Mesh
    Cube058: THREE.Mesh
    Cube061: THREE.Mesh
    Cube066: THREE.Mesh
    Cube067: THREE.Mesh
    Cube068: THREE.Mesh
    Cube070: THREE.Mesh
    Cube073: THREE.Mesh
    Cube075: THREE.Mesh
    Cube077: THREE.Mesh
    Cube079: THREE.Mesh
    Cube080: THREE.Mesh
    Cube081: THREE.Mesh
    Cube091: THREE.Mesh
    Cube093: THREE.Mesh
    Cube094: THREE.Mesh
    Cube095: THREE.Mesh
    Cylinder005: THREE.Mesh
    Cylinder008: THREE.Mesh
    Cylinder011: THREE.Mesh
    Cylinder012: THREE.Mesh
    Cylinder018: THREE.Mesh
    Cylinder023: THREE.Mesh
    Cylinder024: THREE.Mesh
    Cylinder025: THREE.Mesh
    Cylinder026: THREE.Mesh
    Cylinder027: THREE.Mesh
    Cylinder028: THREE.Mesh
    Cylinder029: THREE.Mesh
    Cylinder030: THREE.Mesh
    Mesh019: THREE.Mesh
    Mesh020: THREE.Mesh
    Mesh021: THREE.Mesh
    Mesh022: THREE.Mesh
    Mesh023: THREE.Mesh
    Mesh024: THREE.Mesh
    Mesh025: THREE.Mesh
    Mesh026: THREE.Mesh
    Mesh028: THREE.Mesh
    Mesh029: THREE.Mesh
    Mesh032: THREE.Mesh
    Mesh034: THREE.Mesh
    Mesh037: THREE.Mesh
    Mesh038: THREE.Mesh
    Plane002: THREE.Mesh
    Plane009: THREE.Mesh
    Plane011: THREE.Mesh
    Plane017: THREE.Mesh
    Plane018: THREE.Mesh
    Plane020: THREE.Mesh
    Plane024: THREE.Mesh
    Plane026: THREE.Mesh
    Plane027: THREE.Mesh
    Plane028: THREE.Mesh
    Plane039: THREE.Mesh
    Plane041: THREE.Mesh
    Plane042: THREE.Mesh
    Plane043: THREE.Mesh
    Plane048: THREE.Mesh
    Plane056: THREE.Mesh
    Plane057: THREE.Mesh
    Plane058: THREE.Mesh
    Plane059: THREE.Mesh
    Plane060: THREE.Mesh
    Plane061: THREE.Mesh
    Plane062: THREE.Mesh
    Plane063: THREE.Mesh
    Plane064: THREE.Mesh
    Plane065: THREE.Mesh
    Plane066: THREE.Mesh
    Plane067: THREE.Mesh
    Plane068: THREE.Mesh
    Plane069: THREE.Mesh
    Plane070: THREE.Mesh
    ['WhatsApp_Image_2023-03-19_at_11711_AM_(1)002']: THREE.Mesh
    ['WhatsApp_Image_2023-03-19_at_11711_AM_(1)003']: THREE.Mesh
    ['WhatsApp_Image_2023-05-06_at_95846_AM_copy002']: THREE.Mesh
    ['WhatsApp_Image_2023-05-06_at_95846_AM_copy003']: THREE.Mesh
  }
  materials: {
    shed: THREE.MeshStandardMaterial
    Concrete_Wall_vhjldck: THREE.MeshStandardMaterial
    Galaxy: THREE.MeshStandardMaterial
    ['Timeless Beauty']: THREE.MeshStandardMaterial
    ['Material.053']: THREE.MeshStandardMaterial
    ['Material.041']: THREE.MeshStandardMaterial
    ['Black plastic PL.002']: THREE.MeshStandardMaterial
    ['Tarp Sports Cherry Red Black Topstitch.001']: THREE.MeshStandardMaterial
    ['Material.009']: THREE.MeshStandardMaterial
    ['Material.010']: THREE.MeshStandardMaterial
    ['cart white.001']: THREE.MeshStandardMaterial
    ['Material.022']: THREE.MeshStandardMaterial
    ['Rough Iron Steel.002']: THREE.MeshStandardMaterial
    ['Material.007']: THREE.MeshStandardMaterial
    ['Steel.006']: THREE.MeshStandardMaterial
    ['Dark Steel.001']: THREE.MeshStandardMaterial
    ['Black 1.001']: THREE.MeshStandardMaterial
    ['Stainless Steel.002']: THREE.MeshStandardMaterial
    ['amg_nadbadge.002']: THREE.MeshStandardMaterial
    ['glass_red.001']: THREE.MeshStandardMaterial
    ['CHROME.001']: THREE.MeshStandardMaterial
    ['Back_emit.001']: THREE.MeshStandardMaterial
    ['Material.018']: THREE.MeshStandardMaterial
    ['Material.019']: THREE.MeshStandardMaterial
    ['Material.025']: THREE.MeshStandardMaterial
    ['Material.026']: THREE.MeshStandardMaterial
    ['Material.027']: THREE.MeshStandardMaterial
    ['Steel.001']: THREE.MeshStandardMaterial
    ['Iron Touched.001']: THREE.MeshStandardMaterial
    ['Cold North']: THREE.MeshStandardMaterial
    ['Iron Touched.002']: THREE.MeshStandardMaterial
    ['0black.002']: THREE.MeshStandardMaterial
    ['Glow Glass 02.002']: THREE.MeshStandardMaterial
    ['Black plastic old scratched.002']: THREE.MeshStandardMaterial
    ['Material.031']: THREE.MeshStandardMaterial
    ['Black Plastic.004']: THREE.MeshStandardMaterial
    ['Material.034']: THREE.MeshStandardMaterial
    ['Material.054']: THREE.MeshStandardMaterial
    ['Material.008']: THREE.MeshStandardMaterial
    ['Steel.002']: THREE.MeshStandardMaterial
    ['Black Plastic.003']: THREE.MeshStandardMaterial
    ['Matte Black.002']: THREE.MeshStandardMaterial
    ['Rubber.002']: THREE.MeshStandardMaterial
    ['Material.012']: THREE.MeshStandardMaterial
    ['Dark Steel.004']: THREE.MeshStandardMaterial
    ['Floral Scent']: THREE.MeshStandardMaterial
    ['rubber.002']: THREE.MeshStandardMaterial
    ['Material.028']: THREE.MeshStandardMaterial
    ['Candy Bar']: THREE.MeshStandardMaterial
    Paradise: THREE.MeshStandardMaterial
    ['Material.029']: THREE.MeshStandardMaterial
    ['Material.030']: THREE.MeshStandardMaterial
    ['Material.032']: THREE.MeshStandardMaterial
    ['Black plastic PL.003']: THREE.MeshStandardMaterial
    ['Material.044']: THREE.MeshStandardMaterial
    ['Black plastic PL.001']: THREE.MeshStandardMaterial
    ['Material.003']: THREE.MeshStandardMaterial
    ['BASE.002']: THREE.MeshStandardMaterial
    ['Material.017']: THREE.MeshStandardMaterial
    ['Material.033']: THREE.MeshStandardMaterial
    ['Glass.001']: THREE.MeshStandardMaterial
    ['Material.004']: THREE.MeshStandardMaterial
    ['Material.005']: THREE.MeshStandardMaterial
    ['Dark_metal.002']: THREE.MeshStandardMaterial
    ['Material.006']: THREE.MeshStandardMaterial
    ['Black.002']: THREE.MeshStandardMaterial
    ['metal.002']: THREE.MeshStandardMaterial
    ['Material.013']: THREE.MeshStandardMaterial
    ['Material.014']: THREE.MeshStandardMaterial
    ['Material.016']: THREE.MeshStandardMaterial
    ['Material.020']: THREE.MeshStandardMaterial
    ['cart white.004']: THREE.MeshStandardMaterial
    ['Material.002']: THREE.MeshStandardMaterial
    ['WhatsApp Image 2023-05-06 at 9.58.46 AM copy.002']: THREE.MeshStandardMaterial
  }
}

export function Model(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/models/Kart_Four_Seater.glb') as GLTFResult
  return (
    <group {...props} dispose={null}>
      <Feature4/>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <mesh geometry={nodes.Object_0_1.geometry} material={materials.shed} />
        <mesh geometry={nodes.Object_0_2.geometry} material={materials.Concrete_Wall_vhjldck} />
      </group>
      <group rotation={[-Math.PI / 2, 0, 0]} scale={0.001}>
        <group position={[-338.811, 2855.453, 1462.968]} rotation={[Math.PI / 2, 0, 0]} scale={[8887.125, 8887.127, 8887.127]}>
          <mesh geometry={nodes.Cylinder019.geometry} material={materials.Galaxy} position={[0.52, -0.02, 0.483]} scale={0.113} />
          <mesh geometry={nodes.Cylinder020.geometry} material={materials['Timeless Beauty']} position={[-0.442, -0.02, 0.483]} rotation={[-Math.PI, 0, 0]} scale={-0.113} />
        </group>
        <group position={[-565.827, 7951.263, 5198.166]} rotation={[-Math.PI / 2, Math.PI / 2, 0]} scale={-92.779}>
          <mesh geometry={nodes.Cube015.geometry} material={materials['Material.053']} />
          <mesh geometry={nodes.Cube016.geometry} material={materials['Material.041']} />
        </group>
        <group position={[-26.635, 675.073, 1491.787]} rotation={[-1.024, 0, Math.PI / 2]} scale={[78.124, 113.549, 78.124]}>
          <mesh geometry={nodes.Cube003.geometry} material={materials['Black plastic PL.002']} />
          <mesh geometry={nodes.Cube004.geometry} material={materials['Tarp Sports Cherry Red Black Topstitch.001']} />
        </group>
        <group position={[20.299, -592.572, 1501.7]} rotation={[-1.024, 0, Math.PI / 2]} scale={[78.124, 113.549, 78.124]}>
          <mesh geometry={nodes.Cube005.geometry} material={materials['Black plastic PL.002']} />
          <mesh geometry={nodes.Cube006.geometry} material={materials['Tarp Sports Cherry Red Black Topstitch.001']} />
        </group>
        <group position={[31.531, 899.995, 1327.302]} rotation={[-Math.PI / 2, 0, -Math.PI]} scale={[378.242, 345.848, 386.596]}>
          <mesh geometry={nodes.Cube001.geometry} material={materials['Material.009']} />
          <mesh geometry={nodes.Cube002.geometry} material={materials['Material.010']} />
        </group>
        <group position={[31.531, -307.52, 1370.569]} rotation={[-Math.PI / 2, 0, -Math.PI]} scale={[378.242, 345.848, 386.596]}>
          <mesh geometry={nodes.Cube007.geometry} material={materials['Material.009']} />
          <mesh geometry={nodes.Cube008.geometry} material={materials['Material.010']} />
        </group>
        <group position={[-70.03, -76.898, 1116.326]} rotation={[Math.PI / 2, 0, 0]} scale={443.748}>
          <mesh geometry={nodes.Cube009.geometry} material={materials['cart white.001']} />
          <mesh geometry={nodes.Cube010.geometry} material={materials['Material.022']} />
        </group>
        <group position={[16.518, 3000.954, 109.817]} rotation={[-Math.PI / 2, 0, -Math.PI]} scale={576.976}>
          <group position={[0, 0.893, -0.038]} scale={[0.616, 1, 0.107]}>
            <mesh geometry={nodes.Plane001.geometry} material={materials['Rough Iron Steel.002']} />
            <mesh geometry={nodes.Plane052.geometry} material={materials['Material.007']} position={[-0.084, 0.682, 1.198]} rotation={[2.071, 0, 0]} scale={[0.373, 1.845, 0.092]} />
          </group>
          <mesh geometry={nodes.Cube019.geometry} material={materials['Steel.006']} position={[-1.076, 1.936, -0.016]} rotation={[-0.245, 0, -0.033]} scale={[0.227, 0.227, 0.001]} />
          <mesh geometry={nodes.Cube020.geometry} material={materials['Steel.006']} position={[1.008, 1.896, -0.019]} rotation={[-0.286, 0, 1.087]} scale={[0.227, 0.227, 0.001]} />
          <mesh geometry={nodes.Cube022.geometry} material={materials['Dark Steel.001']} position={[0.003, 0.521, 0.002]} scale={[0.604, 0.044, 0.044]} />
          <mesh geometry={nodes.Cylinder014.geometry} material={materials['Dark Steel.001']} position={[0, 1.929, -0.038]} rotation={[0, 0, -Math.PI / 2]} scale={[0.089, 1.974, 0.089]} />
          <mesh geometry={nodes.Cylinder015.geometry} material={materials['Dark Steel.001']} position={[0, 2.291, -0.049]} rotation={[0, 0, -Math.PI / 2]} scale={[0.043, 0.552, 0.043]} />
          <mesh geometry={nodes.Cylinder017.geometry} material={materials['Rough Iron Steel.002']} position={[0, 0.019, -2.467]} scale={[5.37, 2.912, 2.912]} />
          <mesh geometry={nodes.Plane049.geometry} material={materials['Steel.006']} position={[-0.015, 2.024, -0.014]} rotation={[Math.PI / 2, 0, 0]} scale={[0.898, 1, 0.014]} />
          <mesh geometry={nodes.Plane053.geometry} material={materials['Dark Steel.001']} position={[0, 0.499, -0.083]} scale={[0.415, 0.991, 0.089]} />
        </group>
        <group position={[1102.451, 2726.042, 498.538]} rotation={[Math.PI, 0, Math.PI]} scale={1017.677}>
          <mesh geometry={nodes.hub_rf001.geometry} material={materials['Black 1.001']} />
          <mesh geometry={nodes.hub_rf002.geometry} material={materials['Stainless Steel.002']} />
          <mesh geometry={nodes.hub_rf003.geometry} material={materials['amg_nadbadge.002']} />
        </group>
        <group position={[1102.451, -1206.991, 498.538]} rotation={[Math.PI, 0, Math.PI]} scale={1017.677}>
          <mesh geometry={nodes.hub_rf006.geometry} material={materials['Black 1.001']} />
          <mesh geometry={nodes.hub_rf007.geometry} material={materials['Stainless Steel.002']} />
          <mesh geometry={nodes.hub_rf008.geometry} material={materials['amg_nadbadge.002']} />
        </group>
        <group position={[-1088.39, -1206.991, 498.538]} rotation={[0, 0, Math.PI]} scale={-1017.677}>
          <mesh geometry={nodes.hub_rf010.geometry} material={materials['Black 1.001']} />
          <mesh geometry={nodes.hub_rf011.geometry} material={materials['Stainless Steel.002']} />
          <mesh geometry={nodes.hub_rf012.geometry} material={materials['amg_nadbadge.002']} />
        </group>
        <group position={[-1088.39, 2739.792, 498.538]} rotation={[0, 0, Math.PI]} scale={-1017.677}>
          <mesh geometry={nodes.hub_rf014.geometry} material={materials['Black 1.001']} />
          <mesh geometry={nodes.hub_rf015.geometry} material={materials['Stainless Steel.002']} />
          <mesh geometry={nodes.hub_rf016.geometry} material={materials['amg_nadbadge.002']} />
        </group>
        <group position={[992.312, -1754.343, 1378.976]} rotation={[-1.74, 1.313, -0.325]} scale={[6194.158, 6483.519, 1024.475]}>
          <mesh geometry={nodes.Mesh001.geometry} material={materials['glass_red.001']} />
          <mesh geometry={nodes.Mesh002.geometry} material={materials['CHROME.001']} />
          <mesh geometry={nodes.Mesh003.geometry} material={materials['Back_emit.001']} />
        </group>
        <group position={[8.729, 1865.263, 2821.817]} rotation={[1.787, 0, 0]} scale={72.341}>
          <mesh geometry={nodes.Mesh004.geometry} material={materials['Material.018']} />
          <mesh geometry={nodes.Mesh005.geometry} material={materials['Material.019']} />
        </group>
        <group position={[-957.288, -1752.165, 1378.786]} rotation={[1.343, 1.303, -0.332]} scale={[-6194.159, -6483.518, -1024.475]}>
          <mesh geometry={nodes.Mesh006.geometry} material={materials['glass_red.001']} />
          <mesh geometry={nodes.Mesh007.geometry} material={materials['CHROME.001']} />
          <mesh geometry={nodes.Mesh008.geometry} material={materials['Back_emit.001']} />
        </group>
        <group position={[86.344, 1850.244, 1683.141]} rotation={[Math.PI / 2, 0, 0]} scale={102.623}>
          <mesh geometry={nodes.Mesh009.geometry} material={materials['Material.025']} />
          <mesh geometry={nodes.Mesh010.geometry} material={materials['Material.026']} />
        </group>
        <group position={[-92.26, 1789.067, 1488.832]} rotation={[Math.PI / 2, 0, 0]} scale={116.979}>
          <mesh geometry={nodes.Mesh011.geometry} material={materials['Material.025']} />
          <mesh geometry={nodes.Mesh012.geometry} material={materials['Material.027']} />
        </group>
        <group position={[942.898, 2514.819, 529.359]} rotation={[-Math.PI, 0, 0]} scale={1212.544}>
          <mesh geometry={nodes.suspension_rf001.geometry} material={materials['Black 1.001']} />
          <mesh geometry={nodes.suspension_rf002.geometry} material={materials['Steel.001']} />
        </group>
        <group position={[942.898, -1418.214, 529.359]} rotation={[-Math.PI, 0, 0]} scale={1212.544}>
          <mesh geometry={nodes.suspension_rf003.geometry} material={materials['Black 1.001']} />
          <mesh geometry={nodes.suspension_rf006.geometry} material={materials['Steel.001']} />
        </group>
        <group position={[-928.837, -1418.214, 529.359]} scale={-1212.544}>
          <mesh geometry={nodes.suspension_rf008.geometry} material={materials['Black 1.001']} />
          <mesh geometry={nodes.suspension_rf009.geometry} material={materials['Steel.001']} />
        </group>
        <group position={[-928.837, 2528.569, 529.359]} scale={-1212.544}>
          <mesh geometry={nodes.suspension_rf011.geometry} material={materials['Black 1.001']} />
          <mesh geometry={nodes.suspension_rf012.geometry} material={materials['Steel.001']} />
        </group>
        <mesh geometry={nodes.Bolt006.geometry} material={materials['Iron Touched.001']} position={[406.076, -780.721, 3114.948]} rotation={[-Math.PI / 2, 0, -3.088]} scale={[7402.243, 7402.236, 7402.243]} />
        <mesh geometry={nodes.Bolt008.geometry} material={materials['Cold North']} position={[18.793, 2044.493, 1119.111]} rotation={[-0.546, 0, 0]} scale={3.965} />
        <mesh geometry={nodes.Bolt009.geometry} material={materials['Iron Touched.002']} position={[19.881, 2736.917, 502.258]} scale={[11532.951, 11532.95, 11532.95]} />
        <mesh geometry={nodes.Bolt010.geometry} material={materials['Iron Touched.002']} position={[209.24, 2736.917, 454.51]} scale={[11532.951, 11532.95, 11532.95]} />
        <mesh geometry={nodes.Bolt011.geometry} material={materials['Iron Touched.002']} position={[-156.467, 2736.917, 454.51]} scale={[11345.808, 11345.805, 11345.805]} />
        <mesh geometry={nodes.Bolt012.geometry} material={materials['Iron Touched.002']} position={[204.794, 2736.917, 579.708]} scale={[11348.284, 11348.28, 11348.28]} />
        <mesh geometry={nodes.Bolt013.geometry} material={materials['Iron Touched.002']} position={[-156.467, 2736.917, 579.708]} scale={[11294.356, 11294.354, 11294.354]} />
        <mesh geometry={nodes.Circle.geometry} material={materials['Black plastic PL.002']} position={[865.892, 883.203, 984.544]} rotation={[Math.PI, -0.374, -Math.PI / 2]} scale={[74.035, 76.133, 78.67]} />
        <mesh geometry={nodes.Circle006.geometry} material={materials['0black.002']} position={[0, -1015.498, 2107.54]} rotation={[Math.PI / 2, 0, 0]} scale={136.64} />
        <mesh geometry={nodes.Circle011.geometry} material={materials['Glow Glass 02.002']} position={[507.695, -1633.027, 2870.372]} rotation={[-Math.PI, 0, 0]} scale={-49.079} />
        <mesh geometry={nodes.Circle012.geometry} material={materials['Black plastic old scratched.002']} position={[-559.064, 2006.696, 1101.472]} rotation={[2.006, 0, 0]} scale={61.583} />
        <mesh geometry={nodes.Circle013.geometry} material={materials['Black plastic PL.002']} position={[-851.03, 883.203, 986.444]} rotation={[-Math.PI, 0.375, -Math.PI / 2]} scale={[74.035, 76.069, 78.733]} />
        <mesh geometry={nodes.Circle014.geometry} material={materials['Black plastic PL.002']} position={[900.655, 883.203, 986.444]} rotation={[0, 0.375, -Math.PI / 2]} scale={[-74.035, -76.069, -78.733]} />
        <mesh geometry={nodes.Circle015.geometry} material={materials['Material.031']} position={[-570.255, 1518.645, 1923.685]} rotation={[2.093, 0, 0]} scale={25.626} />
        <mesh geometry={nodes.Circle016.geometry} material={materials['Black Plastic.004']} position={[488.949, 1773.891, 3019.776]} rotation={[-2.945, 0, 0]} scale={1000} />
        <mesh geometry={nodes.Circle017.geometry} material={materials['Material.034']} position={[-1121.007, -1426.788, 521.29]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={[396.762, 452.135, 396.762]} />
        <mesh geometry={nodes.Circle018.geometry} material={materials['Material.034']} position={[-1121.007, 2523.45, 521.29]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={[396.762, 452.135, 396.762]} />
        <mesh geometry={nodes.Circle019.geometry} material={materials['Material.034']} position={[1135.068, -1426.788, 521.29]} rotation={[-Math.PI / 2, 0, -Math.PI / 2]} scale={[-396.762, -452.136, -396.763]} />
        <mesh geometry={nodes.Circle020.geometry} material={materials['Material.034']} position={[1135.068, 2537.2, 521.29]} rotation={[-Math.PI / 2, 0, -Math.PI / 2]} scale={[-396.762, -452.136, -396.763]} />
        <mesh geometry={nodes.Cube011.geometry} material={materials['Material.053']} position={[-11768.534, -776.169, 6216.062]} rotation={[-Math.PI / 2, 0, 0]} scale={-92.779} />
        <mesh geometry={nodes.Cube012.geometry} material={materials['Material.053']} position={[11451.034, -776.169, 6216.062]} rotation={[Math.PI / 2, 0, 0]} scale={92.779} />
        <mesh geometry={nodes.Cube013.geometry} material={materials['Material.053']} position={[-565.827, -8683.288, 5198.166]} rotation={[-Math.PI / 2, -Math.PI / 2, 0]} scale={-92.779} />
        <mesh geometry={nodes.Cube017.geometry} material={materials['Material.054']} position={[31.531, 507.225, 1835.387]} rotation={[-2.88, 0, -Math.PI]} scale={[365.533, 285.453, 316.277]} />
        <mesh geometry={nodes.Cube018.geometry} material={materials['0black.002']} position={[0, -981.416, 1215.643]} rotation={[Math.PI / 2, 0, 0]} scale={1000} />
        <mesh geometry={nodes.Cube025.geometry} material={materials['Material.008']} position={[39.835, 408.22, 182.648]} rotation={[-Math.PI / 2, 0, -Math.PI]} scale={[3490.396, 3490.395, 2937.392]} />
        <mesh geometry={nodes.Cube026.geometry} material={materials['Steel.002']} position={[16.519, 1905.109, 3131.365]} rotation={[-1.378, 0, -Math.PI]} scale={17.886} />
        <mesh geometry={nodes.Cube027.geometry} material={materials['Material.009']} position={[31.531, -666.179, 1792.158]} rotation={[-2.88, 0, -Math.PI]} scale={[365.534, 287.145, 345.848]} />
        <mesh geometry={nodes.Cube028.geometry} material={materials['Black Plastic.003']} position={[29.609, -670.303, 1783.036]} rotation={[-2.88, 0, -Math.PI]} scale={[356.268, 287.145, 363.329]} />
        <mesh geometry={nodes.Cube031.geometry} material={materials['Matte Black.002']} position={[20.604, 332.406, 129.13]} rotation={[-Math.PI / 2, 0, -Math.PI]} scale={[5268.747, 3094.807, 2707.167]} />
        <mesh geometry={nodes.Cube032.geometry} material={materials['Rubber.002']} position={[819.155, 750.087, 2453.063]} rotation={[-Math.PI / 2, 0, 3.044]} scale={2022.002} />
        <mesh geometry={nodes.Cube033.geometry} material={materials['Rubber.002']} position={[-878.912, 1960.854, 2478.121]} rotation={[-Math.PI / 2, 0, -3.036]} scale={[1955.444, 1955.443, 1955.443]} />
        <mesh geometry={nodes.Cube034.geometry} material={materials['Black Plastic.003']} position={[30.45, -894.514, 1669.217]} rotation={[Math.PI / 2, 0, 0]} scale={154.172} />
        <mesh geometry={nodes.Cube036.geometry} material={materials['Black plastic old scratched.002']} position={[30.45, -2029.387, 857.16]} rotation={[Math.PI / 2, 0, 0]} scale={154.172} />
        <mesh geometry={nodes.Cube037.geometry} material={materials['glass_red.001']} position={[-1145.827, -330.211, 709.682]} rotation={[Math.PI / 2, -Math.PI / 2, 0]} scale={154.172} />
        <mesh geometry={nodes.Cube038.geometry} material={materials['glass_red.001']} position={[1197.709, -330.211, 709.682]} rotation={[-Math.PI / 2, -Math.PI / 2, 0]} scale={-154.172} />
        <mesh geometry={nodes.Cube040.geometry} material={materials['Rubber.002']} position={[-878.912, 1960.854, 2478.121]} rotation={[-Math.PI / 2, 0, -3.036]} scale={[1955.444, 1955.443, 1955.443]} />
        <mesh geometry={nodes.Cube041.geometry} material={materials['Steel.002']} position={[-878.912, 1912.531, 2591.252]} rotation={[-Math.PI / 2, 0, -3.036]} scale={[1955.444, 1955.443, 1955.443]} />
        <mesh geometry={nodes.Cube042.geometry} material={materials['Steel.002']} position={[-878.912, 1960.854, 2528.094]} rotation={[-Math.PI / 2, 0, -3.036]} scale={[1955.444, 1955.443, 1955.443]} />
        <mesh geometry={nodes.Cube043.geometry} material={materials['Material.012']} position={[39.834, 4156.926, 64.797]} rotation={[-Math.PI / 2, 0, -Math.PI]} scale={[3664.653, 3664.652, 3664.652]} />
        <mesh geometry={nodes.Cube046.geometry} material={materials['Dark Steel.001']} position={[-8.183, -3160.526, 135.944]} rotation={[-Math.PI / 2, 0, -Math.PI]} scale={[3718.908, 3718.908, 6150.671]} />
        <mesh geometry={nodes.Cube047.geometry} material={materials['Dark Steel.001']} position={[-8.183, 984.916, -103.966]} rotation={[-Math.PI / 2, 0, -Math.PI]} scale={[3154.379, 3971.37, 1902.644]} />
        <mesh geometry={nodes.Cube051.geometry} material={materials['Black plastic PL.002']} position={[7.031, -1964.268, 877.273]} rotation={[Math.PI / 2, 0, 0]} scale={[99.395, 106.506, 96.869]} />
        <mesh geometry={nodes.Cube052.geometry} material={materials['Steel.002']} position={[821.679, 750.087, 2489.407]} rotation={[-Math.PI / 2, 0, 3.044]} scale={2022.002} />
        <mesh geometry={nodes.Cube053.geometry} material={materials['Steel.002']} position={[819.155, 701.764, 2550.395]} rotation={[-Math.PI / 2, 0, 3.044]} scale={2022.002} />
        <mesh geometry={nodes.Cube057.geometry} material={materials['Dark Steel.004']} position={[86.507, -848.237, 496.766]} rotation={[-Math.PI / 2, 0, -Math.PI]} scale={3718.908} />
        <mesh geometry={nodes.Cube058.geometry} material={materials['Black plastic old scratched.002']} position={[1185.798, 430.632, 731.036]} rotation={[-Math.PI / 2, 0, -Math.PI]} scale={[680.906, 345.485, 576.976]} />
        <mesh geometry={nodes.Cube061.geometry} material={materials['Rubber.002']} position={[819.155, 750.087, 2453.063]} rotation={[-Math.PI / 2, 0, 3.044]} scale={2022.002} />
        <mesh geometry={nodes.Cube066.geometry} material={materials['Floral Scent']} position={[28.13, 2016.064, 1239.357]} rotation={[1.06, 0, 0]} scale={[95.411, 78.677, 56.702]} />
        <mesh geometry={nodes.Cube067.geometry} material={materials['Black plastic PL.002']} position={[23.051, 2735.877, 945.049]} rotation={[-1.978, 0, -Math.PI]} scale={[102.811, 84.135, 94.627]} />
        <mesh geometry={nodes.Cube068.geometry} material={materials['Dark Steel.004']} position={[-132.31, 2662.118, 1324.208]} rotation={[Math.PI / 2, 0, 0]} scale={211.879} />
        <mesh geometry={nodes.Cube070.geometry} material={materials['Black Plastic.003']} position={[-267.97, 1690.053, 900.774]} rotation={[-0.995, 0, Math.PI]} scale={[-82.088, -8.938, -148.417]} />
        <mesh geometry={nodes.Cube073.geometry} material={materials['Steel.002']} position={[-791.227, -1081.37, 2940.357]} rotation={[Math.PI / 2, 0, 0]} scale={20.925} />
        <mesh geometry={nodes.Cube075.geometry} material={materials['Black Plastic.003']} position={[-752.12, 1675.173, 902.719]} rotation={[-0.977, 0, -Math.PI]} scale={[-152.262, -8.938, -148.417]} />
        <mesh geometry={nodes.Cube077.geometry} material={materials['Dark Steel.004']} position={[-838.658, 2140.487, 1786.475]} rotation={[-1.566, 0.099, 2.444]} scale={[-48.49, -15.74, -67.633]} />
        <mesh geometry={nodes.Cube079.geometry} material={materials['Dark Steel.004']} position={[830.364, 2138.023, 1646.533]} rotation={[-1.751, 0.001, -2.472]} scale={[-48.49, -15.74, -67.633]} />
        <mesh geometry={nodes.Cube080.geometry} material={materials['Black Plastic.003']} position={[29.609, 475.477, 1812.506]} rotation={[-2.88, 0, -Math.PI]} scale={[356.267, 86.665, 342.784]} />
        <mesh geometry={nodes.Cube081.geometry} material={materials['cart white.001']} position={[19.831, 903.332, 211.576]} rotation={[Math.PI / 2, 0, 0]} scale={[3253.958, 3229.369, 1776.589]} />
        <mesh geometry={nodes.Cube091.geometry} material={materials['rubber.002']} position={[-766.118, -286.06, 2822.242]} rotation={[Math.PI / 2, 0, 0]} scale={73.311} />
        <mesh geometry={nodes.Cube093.geometry} material={materials['rubber.002']} position={[-871.398, -1400.174, 2950.868]} rotation={[Math.PI / 2, 0, 0]} scale={1000} />
        <mesh geometry={nodes.Cube094.geometry} material={materials['Material.028']} position={[92.033, 1700.572, 1415.34]} rotation={[Math.PI / 2, 0, 0]} scale={15.123} />
        <mesh geometry={nodes.Cube095.geometry} material={materials['Material.028']} position={[43.361, 1700.572, 1415.34]} rotation={[Math.PI / 2, 0, 0]} scale={15.123} />
        <mesh geometry={nodes.Cylinder005.geometry} material={materials['Stainless Steel.002']} position={[136.499, -517.392, -21.268]} rotation={[-Math.PI / 2, 0, -Math.PI]} scale={[3664.653, 3664.652, 3664.652]} />
        <mesh geometry={nodes.Cylinder008.geometry} material={materials['Stainless Steel.002']} position={[136.499, -4450.425, -21.268]} rotation={[-Math.PI / 2, 0, -Math.PI]} scale={[3664.653, 3664.652, 3664.652]} />
        <mesh geometry={nodes.Cylinder011.geometry} material={materials['Stainless Steel.002']} position={[-122.438, -4450.425, -21.268]} rotation={[Math.PI / 2, 0, -Math.PI]} scale={[-3664.653, -3664.652, -3664.652]} />
        <mesh geometry={nodes.Cylinder012.geometry} material={materials['Stainless Steel.002']} position={[-122.438, -503.642, -21.268]} rotation={[Math.PI / 2, 0, -Math.PI]} scale={[-3664.653, -3664.652, -3664.652]} />
        <mesh geometry={nodes.Cylinder018.geometry} material={materials['Black Plastic.003']} position={[37.289, -1686.161, 2868.975]} rotation={[-Math.PI, 0, -Math.PI / 2]} scale={61.19} />
        <mesh geometry={nodes.Cylinder023.geometry} material={materials['cart white.001']} position={[-1160.922, -463.684, 878.316]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={22.332} />
        <mesh geometry={nodes.Cylinder024.geometry} material={materials['cart white.001']} position={[-1160.922, -309.747, 878.316]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={22.332} />
        <mesh geometry={nodes.Cylinder025.geometry} material={materials['Candy Bar']} position={[1192.863, -353.319, 878.316]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={22.332} />
        <mesh geometry={nodes.Cylinder026.geometry} material={materials.Paradise} position={[1192.863, -199.382, 878.316]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={22.332} />
        <mesh geometry={nodes.Cylinder027.geometry} material={materials['Material.029']} position={[-18.002, 1706.512, 1436.344]} rotation={[Math.PI / 2, 0, 0]} scale={22.96} />
        <mesh geometry={nodes.Cylinder028.geometry} material={materials['Material.030']} position={[-197.608, 1849.189, 1638.95]} rotation={[Math.PI / 2, 0, 0]} scale={37.938} />
        <mesh geometry={nodes.Cylinder029.geometry} material={materials['Material.032']} position={[-628.323, 1525.286, 1896.475]} rotation={[1.906, 0.275, 1.223]} scale={41.602} />
        <mesh geometry={nodes.Cylinder030.geometry} material={materials['Black plastic PL.003']} position={[440.46, 1907.266, 2937.179]} rotation={[0.22, 1.164, Math.PI / 2]} scale={[1000, 1000, 736.214]} />
        <mesh geometry={nodes.Mesh019.geometry} material={materials['Material.044']} position={[-12731.428, -624.043, 5347.479]} rotation={[-Math.PI / 2, 0, -Math.PI / 2]} scale={2119.806} />
        <mesh geometry={nodes.Mesh020.geometry} material={materials['Material.044']} position={[12261.132, -563.899, 5467.688]} rotation={[Math.PI / 2, 0, Math.PI / 2]} scale={[2119.806, 2119.806, 2119.807]} />
        <mesh geometry={nodes.Mesh021.geometry} material={materials['Black Plastic.003']} position={[30.45, -870.327, 1661.172]} rotation={[Math.PI / 2, 0, 0]} scale={154.172} />
        <mesh geometry={nodes.Mesh022.geometry} material={materials['Black plastic PL.001']} position={[-900.678, -1498.136, 793.04]} rotation={[2.858, -0.112, -1.454]} scale={[724.202, 637.255, 760.914]} />
        <mesh geometry={nodes.Mesh023.geometry} material={materials['Material.003']} position={[24.323, 2918.329, 1542.781]} rotation={[Math.PI / 2, 0, 0]} scale={26.494} />
        <mesh geometry={nodes.Mesh024.geometry} material={materials['BASE.002']} position={[16.82, 408.22, 792.215]} rotation={[-Math.PI / 2, 0, -Math.PI]} scale={[1152.937, 576.976, 576.976]} />
        <mesh geometry={nodes.Mesh025.geometry} material={materials['Matte Black.002']} position={[29.609, -581.874, 1828.636]} rotation={[Math.PI / 2, 0, 0]} scale={1000} />
        <mesh geometry={nodes.Mesh026.geometry} material={materials['Matte Black.002']} position={[29.609, 629.613, 1832.136]} rotation={[Math.PI / 2, 0, 0]} scale={1000} />
        <mesh geometry={nodes.Mesh028.geometry} material={materials['Material.017']} position={[-1178.672, -327.993, 882.621]} rotation={[Math.PI / 2, 0, Math.PI / 2]} scale={209.191} />
        <mesh geometry={nodes.Mesh029.geometry} material={materials['Material.017']} position={[1209.03, -333.734, 882.621]} rotation={[-Math.PI / 2, 0, -Math.PI / 2]} scale={209.191} />
        <mesh geometry={nodes.Mesh032.geometry} material={materials['rubber.002']} position={[812.704, 1047.922, 2827.561]} rotation={[Math.PI / 2, 0, 0]} scale={73.311} />
        <mesh geometry={nodes.Mesh034.geometry} material={materials['Material.025']} position={[-9.02, 1844.342, 1730.171]} rotation={[Math.PI / 2, Math.PI / 2, 0]} scale={239.164} />
        <mesh geometry={nodes.Mesh037.geometry} material={materials['Material.033']} position={[-579.976, 1482.146, 1855.622]} rotation={[-2.691, 0, 0]} scale={56.574} />
        <mesh geometry={nodes.Mesh038.geometry} material={materials['rubber.002']} position={[-768.551, 1047.922, 2827.561]} rotation={[Math.PI / 2, 0, 0]} scale={73.311} />
        <mesh geometry={nodes.Plane002.geometry} material={materials['Glass.001']} position={[14.648, 2027.505, 2258.001]} rotation={[-2.811, 0, -Math.PI]} scale={[861.919, 598.604, 171.603]} />
        <mesh geometry={nodes.Plane009.geometry} material={materials['Material.004']} position={[24.611, 2917.926, 1557.811]} rotation={[Math.PI / 2, 0, 0]} scale={26.494} />
        <mesh geometry={nodes.Plane011.geometry} material={materials['Material.005']} position={[50.532, -2212.479, 2962.989]} rotation={[2.509, 0, 0]} scale={259.409} />
        <mesh geometry={nodes.Plane017.geometry} material={materials['Dark_metal.002']} position={[1142.283, -564.471, 1437.131]} rotation={[2.117, 0, -Math.PI / 2]} scale={[78.124, 113.549, 78.124]} />
        <mesh geometry={nodes.Plane018.geometry} material={materials['Material.041']} position={[-562.494, -9659.639, 4183.246]} rotation={[-Math.PI / 2, 0, -Math.PI]} scale={38.605} />
        <mesh geometry={nodes.Plane020.geometry} material={materials['Dark_metal.002']} position={[-1074.485, -564.471, 1433.923]} rotation={[2.117, 0, Math.PI / 2]} scale={[78.124, 113.549, 78.124]} />
        <mesh geometry={nodes.Plane024.geometry} material={materials['Black plastic old scratched.002']} position={[30.923, -1605.745, 2869.129]} rotation={[-Math.PI, 0, 0]} scale={[61.19, 61.19, 26.673]} />
        <mesh geometry={nodes.Plane026.geometry} material={materials['Material.006']} position={[20.913, 2629.73, 1599.425]} rotation={[Math.PI / 2, 0, 0]} scale={1000} />
        <mesh geometry={nodes.Plane027.geometry} material={materials['Black.002']} position={[-58.501, -1601.838, 2896.686]} rotation={[0.249, Math.PI / 2, 0]} scale={61.19} />
        <mesh geometry={nodes.Plane028.geometry} material={materials['Black 1.001']} position={[-316.412, -1645.398, 2868.975]} rotation={[0, 1.57, 0]} scale={61.19} />
        <mesh geometry={nodes.Plane039.geometry} material={materials['Dark_metal.002']} position={[-1050.375, 667.88, 1438.28]} rotation={[2.117, 0, Math.PI / 2]} scale={[78.124, 113.549, 78.124]} />
        <mesh geometry={nodes.Plane041.geometry} material={materials['Dark_metal.002']} position={[1102.465, 666.264, 1434.854]} rotation={[2.117, 0, -Math.PI / 2]} scale={[78.124, 113.549, 78.124]} />
        <mesh geometry={nodes.Plane042.geometry} material={materials['Steel.001']} position={[-138.723, -1620.999, 3150.654]} rotation={[-0.123, Math.PI / 2, 0]} scale={61.19} />
        <mesh geometry={nodes.Plane043.geometry} material={materials['cart white.001']} position={[22.55, 3220.455, 1734.737]} rotation={[Math.PI / 2, 0, 0]} scale={1000} />
        <mesh geometry={nodes.Plane048.geometry} material={materials['Steel.002']} position={[-652.494, -1075.532, 2202.406]} rotation={[Math.PI / 2, 0, 0]} scale={1000} />
        <mesh geometry={nodes.Plane056.geometry} material={materials['metal.002']} position={[17.997, 3293.648, 1356.637]} rotation={[Math.PI / 2, 0, 0]} scale={1000} />
        <mesh geometry={nodes.Plane057.geometry} material={materials['Material.013']} position={[22.3, 3176.847, 1338.437]} rotation={[Math.PI / 2, 0, 0]} scale={[994.958, 994.959, 994.959]} />
        <mesh geometry={nodes.Plane058.geometry} material={materials['Material.014']} position={[22.3, 3176.847, 1338.437]} rotation={[Math.PI / 2, 0, 0]} scale={[994.958, 994.959, 994.959]} />
        <mesh geometry={nodes.Plane059.geometry} material={materials['Material.016']} position={[-253.635, 1678.782, 925.569]} rotation={[Math.PI / 2, 0, 0]} scale={66.309} />
        <mesh geometry={nodes.Plane060.geometry} material={materials['Material.005']} position={[-1178.283, -336.604, 881.242]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={[65.85, 176.869, 194.419]} />
        <mesh geometry={nodes.Plane061.geometry} material={materials['Material.005']} position={[1208.265, -325.122, 881.242]} rotation={[-Math.PI / 2, 0, Math.PI / 2]} scale={[65.85, 176.869, 194.419]} />
        <mesh geometry={nodes.Plane062.geometry} material={materials['Material.020']} position={[0, 1767.9, 2932.641]} rotation={[Math.PI / 2, 0, 0]} scale={227.754} />
        <mesh geometry={nodes.Plane063.geometry} material={materials['Material.005']} position={[18.375, 3289.184, 997.511]} rotation={[-2.771, 0, -Math.PI]} scale={191.128} />
        <mesh geometry={nodes.Plane064.geometry} material={materials['rubber.002']} position={[22.55, 1943.528, 1734.737]} rotation={[Math.PI / 2, 0, 0]} scale={1000} />
        <mesh geometry={nodes.Plane065.geometry} material={materials['rubber.002']} position={[0, 1305.778, 1202.275]} rotation={[Math.PI / 2, 0, 0]} scale={1063.56} />
        <mesh geometry={nodes.Plane066.geometry} material={materials['Black plastic PL.002']} position={[-402.448, 2393.77, 1303.006]} rotation={[Math.PI / 2, 0, 0]} scale={398.524} />
        <mesh geometry={nodes.Plane067.geometry} material={materials['Black plastic PL.002']} position={[447.216, 2393.77, 1303.006]} rotation={[-Math.PI / 2, 0, 0]} scale={-398.524} />
        <mesh geometry={nodes.Plane068.geometry} material={materials['cart white.004']} position={[22.55, 1986.01, 1734.737]} rotation={[Math.PI / 2, 0, 0]} scale={1000} />
        <mesh geometry={nodes.Plane069.geometry} material={materials['Dark Steel.004']} position={[18.298, -842.778, 3146.612]} rotation={[-Math.PI / 2, 0, -Math.PI]} scale={[1336.967, 1078.318, 1576.089]} />
        <mesh geometry={nodes.Plane070.geometry} material={materials['Glass.001']} position={[17.997, 3293.648, 1356.637]} rotation={[Math.PI / 2, 0, 0]} scale={1000} />
        <mesh geometry={nodes['WhatsApp_Image_2023-03-19_at_11711_AM_(1)002'].geometry} material={materials['Material.002']} position={[18.597, -1913.985, 2993.861]} rotation={[2.5, 0, 0]} scale={250.713} />
        <mesh geometry={nodes['WhatsApp_Image_2023-03-19_at_11711_AM_(1)003'].geometry} material={materials['Material.002']} position={[19.85, 3084.597, 1077.739]} rotation={[-2.761, 0, Math.PI]} scale={184.452} />
        <mesh geometry={nodes['WhatsApp_Image_2023-05-06_at_95846_AM_copy002'].geometry} material={materials['WhatsApp Image 2023-05-06 at 9.58.46 AM copy.002']} position={[840.598, -1014.185, 1757.03]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={225.914} />
        <mesh geometry={nodes['WhatsApp_Image_2023-05-06_at_95846_AM_copy003'].geometry} material={materials['WhatsApp Image 2023-05-06 at 9.58.46 AM copy.002']} position={[-843.455, -1014.185, 1757.03]} rotation={[-Math.PI / 2, 0, Math.PI / 2]} scale={225.914} />
      </group>
    </group>
  )
}

useGLTF.preload('/models/Kart_Four_Seater.glb')
