/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.11 ./public/models/rims/Rim 4.glb --t
*/

import * as THREE from 'three'
import React, { useRef } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    ['RIMS-4']: THREE.Mesh
  }
  materials: {}
}

type ActionName = 'RIMS-4'
type GLTFActions = Record<ActionName, THREE.AnimationAction>

export function RimModel4(props: JSX.IntrinsicElements['group']) {
  const group = useRef<THREE.Group>()
  const { nodes, materials, animations } = useGLTF('/models/rims/Rim 4.glb') as GLTFResult
  const { actions } = useAnimations<GLTFActions>(animations, group)
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <mesh name="RIMS-4" geometry={nodes['RIMS-4'].geometry} material={nodes['RIMS-4'].material} position={[1.15, 0.14, -2.51]} scale={1.01} />
      </group>
    </group>
  )
}

useGLTF.preload('/models/rims/Rim 4.glb')
