/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.11 ./public/models/rims/Rim 5.glb --t
*/

import * as THREE from 'three'
import React, { useRef } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    ['RIMS-5']: THREE.Mesh
  }
  materials: {}
}

type ActionName = 'RIMS-5'
type GLTFActions = Record<ActionName, THREE.AnimationAction>

export function RimModel5(props: JSX.IntrinsicElements['group']) {
  const group = useRef<THREE.Group>()
  const { nodes, materials, animations } = useGLTF('/models/rims/Rim 5.glb') as GLTFResult
  const { actions } = useAnimations<GLTFActions>(animations, group)
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <mesh name="RIMS-5" geometry={nodes['RIMS-5'].geometry} material={nodes['RIMS-5'].material} position={[1.22, 0.53, -2.5]} rotation={[-0.39, 0, 0]} scale={[0.41, 1.35, 1.35]} />
      </group>
    </group>
  )
}

useGLTF.preload('/models/rims/Rim 5.glb')
