/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.11 ./public/models/rims/Rim 6.glb --t
*/

import * as THREE from 'three'
import React, { useRef } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    ['rims-6']: THREE.Mesh
  }
  materials: {}
}

type ActionName = 'rims-6'
type GLTFActions = Record<ActionName, THREE.AnimationAction>

export function RimModel6(props: JSX.IntrinsicElements['group']) {
  const group = useRef<THREE.Group>()
  const { nodes, materials, animations } = useGLTF('/models/rims/Rim 6.glb') as GLTFResult
  const { actions } = useAnimations<GLTFActions>(animations, group)
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <mesh name="rims-6" geometry={nodes['rims-6'].geometry} material={nodes['rims-6'].material} position={[1.31, 0.53, -2.5]} scale={[0.48, 1.03, 1.03]} />
      </group>
    </group>
  )
}

useGLTF.preload('/models/rims/Rim 6.glb')
