/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.11 ./public/models/rims/Rim 8.glb --t
*/

import * as THREE from 'three'
import React, { useRef } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    ['rims-8']: THREE.Mesh
  }
  materials: {}
}

type ActionName = 'rims-8'
type GLTFActions = Record<ActionName, THREE.AnimationAction>

export function RimModel8(props: JSX.IntrinsicElements['group']) {
  const group = useRef<THREE.Group>()
  const { nodes, materials, animations } = useGLTF('/models/rims/Rim 8.glb') as GLTFResult
  const { actions } = useAnimations<GLTFActions>(animations, group)
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <mesh name="rims-8" geometry={nodes['rims-8'].geometry} material={nodes['rims-8'].material} position={[-1.19, 0.53, 1.42]} rotation={[3.13, 0, Math.PI / 2]} scale={0.22} />
      </group>
    </group>
  )
}

useGLTF.preload('/models/rims/Rim 8.glb')
