/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.11 ./public/models/rims/Rim 9.glb --t
*/

import * as THREE from 'three'
import React, { useRef } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    ['rims-9']: THREE.Mesh
  }
  materials: {}
}

type ActionName = 'rims-9'
type GLTFActions = Record<ActionName, THREE.AnimationAction>

export function RimModel9(props: JSX.IntrinsicElements['group']) {
  const group = useRef<THREE.Group>(null)
  const { nodes, materials, animations } = useGLTF('/models/rims/Rim 9.glb') as GLTFResult
  const { actions } = useAnimations<any>(animations, group)
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <mesh name="rims-9" geometry={nodes['rims-9'].geometry} material={nodes['rims-9'].material} position={[-1.3, 0.52, 1.44]} rotation={[0, 0, -Math.PI / 2]} scale={0.22} />
      </group>
    </group>
  )
}

useGLTF.preload('/models/rims/Rim 9.glb')
