/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.11 SEATREST.glb --t
*/

import * as THREE from 'three'
import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    Cube084: THREE.Mesh
    Cube083_1: THREE.Mesh
    Cube083_2: THREE.Mesh
    Cube074_1: THREE.Mesh
    Cube074_2: THREE.Mesh
  }
  materials: {
    ['Material.023']: THREE.MeshStandardMaterial
    ['Material.014']: THREE.MeshStandardMaterial
  }
}

export function SeatRestModel(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/models/SEATREST.glb') as GLTFResult
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Cube084.geometry} material={materials['Material.023']} position={[0.03, 1.79, 0.69]} rotation={[1.83, 0, Math.PI]} scale={[0.37, 0.29, 0.35]} />
      <group position={[0.03, 1.82, -0.5]} rotation={[1.83, 0, Math.PI]} scale={[0.37, 0.35, 0.31]}>
        <mesh geometry={nodes.Cube083_1.geometry} material={materials['Material.023']} />
        <mesh geometry={nodes.Cube083_2.geometry} material={materials['Material.014']} />
      </group>
      <group position={[0.03, 1.92, 1.36]} rotation={[1.34, 0, 0]} scale={[0.37, 0.35, 0.35]}>
        <mesh geometry={nodes.Cube074_1.geometry} material={materials['Material.023']} />
        <mesh geometry={nodes.Cube074_2.geometry} material={materials['Material.014']} />
      </group>
    </group>
  )
}

useGLTF.preload('/models/SEATREST.glb')
