/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.3 Six_Seater_Kart.glb --t
*/

import * as THREE from 'three'
import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'
import Features, { Feature4 } from './Feature'

type GLTFResult = GLTF & {
  nodes: {
    Object_0_1: THREE.Mesh
    Object_0_2: THREE.Mesh
    Cube002: THREE.Mesh
    Cube003: THREE.Mesh
    Cube030: THREE.Mesh
    Cube031: THREE.Mesh
    Cube012: THREE.Mesh
    Cube014: THREE.Mesh
    Cube018: THREE.Mesh
    Cube019: THREE.Mesh
    Cube010: THREE.Mesh
    Cube011: THREE.Mesh
    Cube008: THREE.Mesh
    Cube009: THREE.Mesh
    Cube006: THREE.Mesh
    Cube007: THREE.Mesh
    Cube004: THREE.Mesh
    Cube005: THREE.Mesh
    hub_rf005: THREE.Mesh
    hub_rf006: THREE.Mesh
    hub_rf007: THREE.Mesh
    hub_rf009: THREE.Mesh
    hub_rf011: THREE.Mesh
    hub_rf012: THREE.Mesh
    hub_rf001: THREE.Mesh
    hub_rf002: THREE.Mesh
    hub_rf003: THREE.Mesh
    hub_rf014: THREE.Mesh
    hub_rf015: THREE.Mesh
    hub_rf016: THREE.Mesh
    Mesh008: THREE.Mesh
    Mesh009: THREE.Mesh
    Mesh010: THREE.Mesh
    Mesh014: THREE.Mesh
    Mesh015: THREE.Mesh
    Mesh017: THREE.Mesh
    Mesh018: THREE.Mesh
    Mesh021: THREE.Mesh
    Mesh025: THREE.Mesh
    Mesh026: THREE.Mesh
    Mesh028: THREE.Mesh
    Mesh029: THREE.Mesh
    Plane005: THREE.Mesh
    Plane023: THREE.Mesh
    suspension_rf004: THREE.Mesh
    suspension_rf005: THREE.Mesh
    suspension_rf007: THREE.Mesh
    suspension_rf008: THREE.Mesh
    suspension_rf001: THREE.Mesh
    suspension_rf002: THREE.Mesh
    suspension_rf011: THREE.Mesh
    suspension_rf012: THREE.Mesh
    Bolt001: THREE.Mesh
    Bolt002: THREE.Mesh
    Bolt003: THREE.Mesh
    Bolt004: THREE.Mesh
    Bolt005: THREE.Mesh
    Bolt007: THREE.Mesh
    Bolt020: THREE.Mesh
    Bolt022: THREE.Mesh
    Circle: THREE.Mesh
    Circle001: THREE.Mesh
    Circle002: THREE.Mesh
    Circle003: THREE.Mesh
    Circle004: THREE.Mesh
    Circle007: THREE.Mesh
    Circle008: THREE.Mesh
    Circle009: THREE.Mesh
    Circle010: THREE.Mesh
    Circle011: THREE.Mesh
    Circle014: THREE.Mesh
    Cube013: THREE.Mesh
    Cube015: THREE.Mesh
    Cube016: THREE.Mesh
    Cube017: THREE.Mesh
    Cube020: THREE.Mesh
    Cube021: THREE.Mesh
    Cube022: THREE.Mesh
    Cube023: THREE.Mesh
    Cube024: THREE.Mesh
    Cube025: THREE.Mesh
    Cube026: THREE.Mesh
    Cube027: THREE.Mesh
    Cube028: THREE.Mesh
    Cube032: THREE.Mesh
    Cube033: THREE.Mesh
    Cube034: THREE.Mesh
    Cube035: THREE.Mesh
    Cube036: THREE.Mesh
    Cube037: THREE.Mesh
    Cube038: THREE.Mesh
    Cube039: THREE.Mesh
    Cube041: THREE.Mesh
    Cube042: THREE.Mesh
    Cube043: THREE.Mesh
    Cube048: THREE.Mesh
    Cube049: THREE.Mesh
    Cube050: THREE.Mesh
    Cube054: THREE.Mesh
    Cube055: THREE.Mesh
    Cube056: THREE.Mesh
    Cube059: THREE.Mesh
    Cube060: THREE.Mesh
    Cube062: THREE.Mesh
    Cube063: THREE.Mesh
    Cube069: THREE.Mesh
    Cube072: THREE.Mesh
    Cube076: THREE.Mesh
    Cube078: THREE.Mesh
    Cube080: THREE.Mesh
    Cube084: THREE.Mesh
    Cube086: THREE.Mesh
    Cube087: THREE.Mesh
    Cube088: THREE.Mesh
    Cube089: THREE.Mesh
    Cube090: THREE.Mesh
    Cylinder: THREE.Mesh
    Cylinder001: THREE.Mesh
    Cylinder002: THREE.Mesh
    Cylinder003: THREE.Mesh
    Cylinder004: THREE.Mesh
    Cylinder006: THREE.Mesh
    Cylinder007: THREE.Mesh
    Cylinder009: THREE.Mesh
    Cylinder010: THREE.Mesh
    Cylinder012: THREE.Mesh
    Cylinder013: THREE.Mesh
    Cylinder016: THREE.Mesh
    Cylinder019: THREE.Mesh
    Cylinder020: THREE.Mesh
    Cylinder021: THREE.Mesh
    Cylinder022: THREE.Mesh
    Cylinder031: THREE.Mesh
    Cylinder040: THREE.Mesh
    Cylinder041: THREE.Mesh
    Cylinder043: THREE.Mesh
    Mesh: THREE.Mesh
    Mesh001: THREE.Mesh
    Mesh002: THREE.Mesh
    Mesh003: THREE.Mesh
    Mesh004: THREE.Mesh
    Mesh005: THREE.Mesh
    Mesh006: THREE.Mesh
    Mesh011: THREE.Mesh
    Mesh012: THREE.Mesh
    Mesh019: THREE.Mesh
    Mesh020: THREE.Mesh
    Mesh022: THREE.Mesh
    Mesh023: THREE.Mesh
    Mesh030: THREE.Mesh
    Mesh031: THREE.Mesh
    Plane: THREE.Mesh
    Plane001: THREE.Mesh
    Plane002: THREE.Mesh
    Plane003: THREE.Mesh
    Plane004: THREE.Mesh
    Plane006: THREE.Mesh
    Plane010: THREE.Mesh
    Plane013: THREE.Mesh
    Plane014: THREE.Mesh
    Plane015: THREE.Mesh
    Plane016: THREE.Mesh
    Plane018: THREE.Mesh
    Plane019: THREE.Mesh
    Plane021: THREE.Mesh
    Plane022: THREE.Mesh
    Plane025: THREE.Mesh
    Plane026: THREE.Mesh
    Plane029: THREE.Mesh
    Plane030: THREE.Mesh
    Plane031: THREE.Mesh
    Plane032: THREE.Mesh
    Plane033: THREE.Mesh
    Plane034: THREE.Mesh
    Plane035: THREE.Mesh
    Plane036: THREE.Mesh
    Plane037: THREE.Mesh
    Plane038: THREE.Mesh
    Plane039: THREE.Mesh
    Plane040: THREE.Mesh
    Plane041: THREE.Mesh
    Plane042: THREE.Mesh
    Plane044: THREE.Mesh
    Plane045: THREE.Mesh
    Plane047: THREE.Mesh
    Plane048: THREE.Mesh
    Plane050: THREE.Mesh
    Plane054: THREE.Mesh
    Plane070: THREE.Mesh
    ['WhatsApp_Image_2023-03-19_at_11711_AM_(1)001']: THREE.Mesh
    ['WhatsApp_Image_2023-03-19_at_11711_AM_(1)004']: THREE.Mesh
    ['WhatsApp_Image_2023-05-06_at_95846_AM_copy']: THREE.Mesh
    ['WhatsApp_Image_2023-05-06_at_95846_AM_copy001']: THREE.Mesh
  }
  materials: {
    shed: THREE.MeshStandardMaterial
    Concrete_Wall_vhjldck: THREE.MeshStandardMaterial
    ['Material.021']: THREE.MeshStandardMaterial
    ['Material.017']: THREE.MeshStandardMaterial
    ['Material.041']: THREE.MeshStandardMaterial
    ['Material.042']: THREE.MeshStandardMaterial
    ['Black plastic PL.004']: THREE.MeshStandardMaterial
    ['Tarp Sports Cherry Red Black Topstitch.003']: THREE.MeshStandardMaterial
    ['Material.043']: THREE.MeshStandardMaterial
    ['Black 1.002']: THREE.MeshStandardMaterial
    ['Stainless Steel.001']: THREE.MeshStandardMaterial
    ['amg_nadbadge.001']: THREE.MeshStandardMaterial
    ['glass_red.002']: THREE.MeshStandardMaterial
    ['CHROME.002']: THREE.MeshStandardMaterial
    ['Back_emit.002']: THREE.MeshStandardMaterial
    ['Material.050']: THREE.MeshStandardMaterial
    ['Material.051']: THREE.MeshStandardMaterial
    ['Material.053']: THREE.MeshStandardMaterial
    ['Material.054']: THREE.MeshStandardMaterial
    ['Material.055']: THREE.MeshStandardMaterial
    ['Rough Iron Steel.001']: THREE.MeshStandardMaterial
    ['Material.062']: THREE.MeshStandardMaterial
    ['Steel.003']: THREE.MeshStandardMaterial
    ['Iron Touched.004']: THREE.MeshStandardMaterial
    Melody: THREE.MeshStandardMaterial
    ['Iron Touched.003']: THREE.MeshStandardMaterial
    ['Black plastic old scratched.001']: THREE.MeshStandardMaterial
    ['Glow Glass 02.001']: THREE.MeshStandardMaterial
    ['0black.001']: THREE.MeshStandardMaterial
    ['Material.059']: THREE.MeshStandardMaterial
    ['Material.024']: THREE.MeshStandardMaterial
    ['Rubber.001']: THREE.MeshStandardMaterial
    ['Dark Steel.003']: THREE.MeshStandardMaterial
    ['Black Plastic.001']: THREE.MeshStandardMaterial
    ['Steel.004']: THREE.MeshStandardMaterial
    Melissa: THREE.MeshStandardMaterial
    ['cart white.002']: THREE.MeshStandardMaterial
    ['rubber.001']: THREE.MeshStandardMaterial
    ['Material.056']: THREE.MeshStandardMaterial
    ['Dark Steel.002']: THREE.MeshStandardMaterial
    ['Material.045']: THREE.MeshStandardMaterial
    ['Matte Black.001']: THREE.MeshStandardMaterial
    ['Steel.005']: THREE.MeshStandardMaterial
    ['Material.040']: THREE.MeshStandardMaterial
    ['Ocean Tropic']: THREE.MeshStandardMaterial
    Alexa: THREE.MeshStandardMaterial
    ['Pure Passion']: THREE.MeshStandardMaterial
    ['Material.057']: THREE.MeshStandardMaterial
    ['Material.058']: THREE.MeshStandardMaterial
    ['Material.060']: THREE.MeshStandardMaterial
    ['Glossy Tint']: THREE.MeshStandardMaterial
    ['Black plastic PL.007']: THREE.MeshStandardMaterial
    Afternoon: THREE.MeshStandardMaterial
    Havana: THREE.MeshStandardMaterial
    ['Material.036']: THREE.MeshStandardMaterial
    ['BASE.001']: THREE.MeshStandardMaterial
    ['Black plastic PL.005']: THREE.MeshStandardMaterial
    ['Material.049']: THREE.MeshStandardMaterial
    ['Material.019']: THREE.MeshStandardMaterial
    ['Material.061']: THREE.MeshStandardMaterial
    ['Material.048']: THREE.MeshStandardMaterial
    ['Black plastic PL.006']: THREE.MeshStandardMaterial
    ['metal.001']: THREE.MeshStandardMaterial
    ['Material.046']: THREE.MeshStandardMaterial
    ['Material.038']: THREE.MeshStandardMaterial
    ['Black.001']: THREE.MeshStandardMaterial
    ['Material.039']: THREE.MeshStandardMaterial
    ['Material.047']: THREE.MeshPhysicalMaterial
    ['Material.052']: THREE.MeshStandardMaterial
    ['Tarp Sports Cherry Red Black Topstitch.002']: THREE.MeshStandardMaterial
    ['Dark_metal.001']: THREE.MeshStandardMaterial
    ['Glass.002']: THREE.MeshStandardMaterial
    ['cart white.003']: THREE.MeshStandardMaterial
    ['Material.037']: THREE.MeshStandardMaterial
    ['Material.035']: THREE.MeshStandardMaterial
    ['WhatsApp Image 2023-05-06 at 9.58.46 AM copy.001']: THREE.MeshStandardMaterial
  }
}

export function Model(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/models/Six_Seater_Kart.glb') as GLTFResult
  return (
    <group {...props} dispose={null}>
      <Features/>
      <group rotation={[-Math.PI / 2, 0, 0]} scale={0.001}>
        <group rotation={[Math.PI / 2, 0, 0]} scale={1000}>
          <mesh geometry={nodes.Cube002.geometry} material={materials['Material.021']} />
          <mesh geometry={nodes.Cube003.geometry} material={materials['Material.017']} />
        </group>
        <group rotation={[Math.PI / 2, 0, 0]} scale={1000}>
          <mesh geometry={nodes.Cube030.geometry} material={materials['Material.041']} />
          <mesh geometry={nodes.Cube031.geometry} material={materials['Material.042']} />
        </group>
        <group rotation={[Math.PI / 2, 0, 0]} scale={1000}>
          <mesh geometry={nodes.Cube012.geometry} material={materials['Black plastic PL.004']} />
          <mesh geometry={nodes.Cube014.geometry} material={materials['Tarp Sports Cherry Red Black Topstitch.003']} />
        </group>
        <group rotation={[Math.PI / 2, 0, 0]} scale={1000}>
          <mesh geometry={nodes.Cube018.geometry} material={materials['Black plastic PL.004']} />
          <mesh geometry={nodes.Cube019.geometry} material={materials['Tarp Sports Cherry Red Black Topstitch.003']} />
        </group>
        <group rotation={[Math.PI / 2, 0, 0]} scale={1000}>
          <mesh geometry={nodes.Cube010.geometry} material={materials['Black plastic PL.004']} />
          <mesh geometry={nodes.Cube011.geometry} material={materials['Tarp Sports Cherry Red Black Topstitch.003']} />
        </group>
        <group rotation={[Math.PI / 2, 0, 0]} scale={1000}>
          <mesh geometry={nodes.Cube008.geometry} material={materials['Material.041']} />
          <mesh geometry={nodes.Cube009.geometry} material={materials['Material.042']} />
        </group>
        <group rotation={[Math.PI / 2, 0, 0]} scale={1000}>
          <mesh geometry={nodes.Cube006.geometry} material={materials['Material.041']} />
          <mesh geometry={nodes.Cube007.geometry} material={materials['Material.043']} />
        </group>
        <group rotation={[Math.PI / 2, 0, 0]} scale={1000}>
          <mesh geometry={nodes.Cube004.geometry} material={materials['Material.041']} />
          <mesh geometry={nodes.Cube005.geometry} material={materials['Material.042']} />
        </group>
        <group rotation={[Math.PI / 2, 0, 0]} scale={1000}>
          <mesh geometry={nodes.hub_rf005.geometry} material={materials['Black 1.002']} />
          <mesh geometry={nodes.hub_rf006.geometry} material={materials['Stainless Steel.001']} />
          <mesh geometry={nodes.hub_rf007.geometry} material={materials['amg_nadbadge.001']} />
        </group>
        <group rotation={[Math.PI / 2, 0, 0]} scale={1000}>
          <mesh geometry={nodes.hub_rf009.geometry} material={materials['Black 1.002']} />
          <mesh geometry={nodes.hub_rf011.geometry} material={materials['Stainless Steel.001']} />
          <mesh geometry={nodes.hub_rf012.geometry} material={materials['amg_nadbadge.001']} />
        </group>
        <group rotation={[Math.PI / 2, 0, 0]} scale={1000}>
          <mesh geometry={nodes.hub_rf001.geometry} material={materials['Black 1.002']} />
          <mesh geometry={nodes.hub_rf002.geometry} material={materials['Stainless Steel.001']} />
          <mesh geometry={nodes.hub_rf003.geometry} material={materials['amg_nadbadge.001']} />
        </group>
        <group rotation={[Math.PI / 2, 0, 0]} scale={1000}>
          <mesh geometry={nodes.hub_rf014.geometry} material={materials['Black 1.002']} />
          <mesh geometry={nodes.hub_rf015.geometry} material={materials['Stainless Steel.001']} />
          <mesh geometry={nodes.hub_rf016.geometry} material={materials['amg_nadbadge.001']} />
        </group>
        <group rotation={[Math.PI / 2, 0, 0]} scale={1000}>
          <mesh geometry={nodes.Mesh008.geometry} material={materials['glass_red.002']} />
          <mesh geometry={nodes.Mesh009.geometry} material={materials['CHROME.002']} />
          <mesh geometry={nodes.Mesh010.geometry} material={materials['Back_emit.002']} />
        </group>
        <group rotation={[Math.PI / 2, 0, 0]} scale={1000}>
          <mesh geometry={nodes.Mesh014.geometry} material={materials['Material.050']} />
          <mesh geometry={nodes.Mesh015.geometry} material={materials['Material.051']} />
        </group>
        <group rotation={[Math.PI / 2, 0, 0]} scale={1000}>
          <mesh geometry={nodes.Mesh017.geometry} material={materials['glass_red.002']} />
          <mesh geometry={nodes.Mesh018.geometry} material={materials['CHROME.002']} />
          <mesh geometry={nodes.Mesh021.geometry} material={materials['Back_emit.002']} />
        </group>
        <group rotation={[Math.PI / 2, 0, 0]} scale={1000}>
          <mesh geometry={nodes.Mesh025.geometry} material={materials['Material.053']} />
          <mesh geometry={nodes.Mesh026.geometry} material={materials['Material.054']} />
        </group>
        <group rotation={[Math.PI / 2, 0, 0]} scale={1000}>
          <mesh geometry={nodes.Mesh028.geometry} material={materials['Material.053']} />
          <mesh geometry={nodes.Mesh029.geometry} material={materials['Material.055']} />
        </group>
        <group rotation={[Math.PI / 2, 0, 0]} scale={1000}>
          <mesh geometry={nodes.Plane005.geometry} material={materials['Rough Iron Steel.001']} />
          <mesh geometry={nodes.Plane023.geometry} material={materials['Material.062']} />
        </group>
        <group rotation={[Math.PI / 2, 0, 0]} scale={1000}>
          <mesh geometry={nodes.suspension_rf004.geometry} material={materials['Black 1.002']} />
          <mesh geometry={nodes.suspension_rf005.geometry} material={materials['Steel.003']} />
        </group>
        <group rotation={[Math.PI / 2, 0, 0]} scale={1000}>
          <mesh geometry={nodes.suspension_rf007.geometry} material={materials['Black 1.002']} />
          <mesh geometry={nodes.suspension_rf008.geometry} material={materials['Steel.003']} />
        </group>
        <group rotation={[Math.PI / 2, 0, 0]} scale={1000}>
          <mesh geometry={nodes.suspension_rf001.geometry} material={materials['Black 1.002']} />
          <mesh geometry={nodes.suspension_rf002.geometry} material={materials['Steel.003']} />
        </group>
        <group rotation={[Math.PI / 2, 0, 0]} scale={1000}>
          <mesh geometry={nodes.suspension_rf011.geometry} material={materials['Black 1.002']} />
          <mesh geometry={nodes.suspension_rf012.geometry} material={materials['Steel.003']} />
        </group>
        <mesh geometry={nodes.Bolt001.geometry} material={materials['Iron Touched.004']} rotation={[Math.PI / 2, 0, 0]} scale={1000} />
        <mesh geometry={nodes.Bolt002.geometry} material={materials['Iron Touched.004']} rotation={[Math.PI / 2, 0, 0]} scale={1000} />
        <mesh geometry={nodes.Bolt003.geometry} material={materials['Iron Touched.004']} rotation={[Math.PI / 2, 0, 0]} scale={1000} />
        <mesh geometry={nodes.Bolt004.geometry} material={materials['Iron Touched.004']} rotation={[Math.PI / 2, 0, 0]} scale={1000} />
        <mesh geometry={nodes.Bolt005.geometry} material={materials['Iron Touched.004']} rotation={[Math.PI / 2, 0, 0]} scale={1000} />
        <mesh geometry={nodes.Bolt007.geometry} material={materials.Melody} rotation={[Math.PI / 2, 0, 0]} scale={1000} />
        <mesh geometry={nodes.Bolt020.geometry} material={materials['Iron Touched.003']} rotation={[Math.PI / 2, 0, 0]} scale={1000} />
        <mesh geometry={nodes.Bolt022.geometry} material={materials['Iron Touched.003']} rotation={[Math.PI / 2, 0, 0]} scale={1000} />
        <mesh geometry={nodes.Circle.geometry} material={materials['Black plastic PL.004']} rotation={[Math.PI / 2, 0, 0]} scale={1000} />
        <mesh geometry={nodes.Circle001.geometry} material={materials['Black plastic PL.004']} rotation={[Math.PI / 2, 0, 0]} scale={1000} />
        <mesh geometry={nodes.Circle002.geometry} material={materials['Black plastic old scratched.001']} rotation={[Math.PI / 2, 0, 0]} scale={1000} />
        <mesh geometry={nodes.Circle003.geometry} material={materials['Glow Glass 02.001']} rotation={[Math.PI / 2, 0, 0]} scale={1000} />
        <mesh geometry={nodes.Circle004.geometry} material={materials['Black plastic PL.004']} rotation={[Math.PI / 2, 0, 0]} scale={1000} />
        <mesh geometry={nodes.Circle007.geometry} material={materials['0black.001']} rotation={[Math.PI / 2, 0, 0]} scale={1000} />
        <mesh geometry={nodes.Circle008.geometry} material={materials['Material.059']} rotation={[Math.PI / 2, 0, 0]} scale={1000} />
        <mesh geometry={nodes.Circle009.geometry} material={materials['Material.024']} rotation={[Math.PI / 2, 0, 0]} scale={1000} />
        <mesh geometry={nodes.Circle010.geometry} material={materials['Material.024']} rotation={[Math.PI / 2, 0, 0]} scale={1000} />
        <mesh geometry={nodes.Circle011.geometry} material={materials['Material.024']} rotation={[Math.PI / 2, 0, 0]} scale={1000} />
        <mesh geometry={nodes.Circle014.geometry} material={materials['Material.024']} rotation={[Math.PI / 2, 0, 0]} scale={1000} />
        <mesh geometry={nodes.Cube013.geometry} material={materials['Material.021']} rotation={[Math.PI / 2, 0, 0]} scale={1000} />
        <mesh geometry={nodes.Cube015.geometry} material={materials['Rubber.001']} rotation={[Math.PI / 2, 0, 0]} scale={1000} />
        <mesh geometry={nodes.Cube016.geometry} material={materials['Black plastic old scratched.001']} rotation={[Math.PI / 2, 0, 0]} scale={1000} />
        <mesh geometry={nodes.Cube017.geometry} material={materials['Dark Steel.003']} rotation={[Math.PI / 2, 0, 0]} scale={1000} />
        <mesh geometry={nodes.Cube020.geometry} material={materials['Black Plastic.001']} rotation={[Math.PI / 2, 0, 0]} scale={1000} />
        <mesh geometry={nodes.Cube021.geometry} material={materials['Dark Steel.003']} rotation={[Math.PI / 2, 0, 0]} scale={1000} />
        <mesh geometry={nodes.Cube022.geometry} material={materials['Steel.004']} rotation={[Math.PI / 2, 0, 0]} scale={1000} />
        <mesh geometry={nodes.Cube023.geometry} material={materials['Black plastic PL.004']} rotation={[Math.PI / 2, 0, 0]} scale={1000} />
        <mesh geometry={nodes.Cube024.geometry} material={materials.Melissa} rotation={[Math.PI / 2, 0, 0]} scale={1000} />
        <mesh geometry={nodes.Cube025.geometry} material={materials['Black Plastic.001']} rotation={[Math.PI / 2, 0, 0]} scale={1000} />
        <mesh geometry={nodes.Cube026.geometry} material={materials['Dark Steel.003']} rotation={[Math.PI / 2, 0, 0]} scale={1000} />
        <mesh geometry={nodes.Cube027.geometry} material={materials['Dark Steel.003']} rotation={[Math.PI / 2, 0, 0]} scale={1000} />
        <mesh geometry={nodes.Cube028.geometry} material={materials['cart white.002']} rotation={[Math.PI / 2, 0, 0]} scale={1000} />
        <mesh geometry={nodes.Cube032.geometry} material={materials['rubber.001']} rotation={[Math.PI / 2, 0, 0]} scale={1000} />
        <mesh geometry={nodes.Cube033.geometry} material={materials['rubber.001']} rotation={[Math.PI / 2, 0, 0]} scale={1000} />
        <mesh geometry={nodes.Cube034.geometry} material={materials['0black.001']} rotation={[Math.PI / 2, 0, 0]} scale={1000} />
        <mesh geometry={nodes.Cube035.geometry} material={materials['Rubber.001']} rotation={[Math.PI / 2, 0, 0]} scale={1000} />
        <mesh geometry={nodes.Cube036.geometry} material={materials['rubber.001']} rotation={[Math.PI / 2, 0, 0]} scale={1000} />
        <mesh geometry={nodes.Cube037.geometry} material={materials['cart white.002']} rotation={[Math.PI / 2, 0, 0]} scale={1000} />
        <mesh geometry={nodes.Cube038.geometry} material={materials['rubber.001']} rotation={[Math.PI / 2, 0, 0]} scale={1000} />
        <mesh geometry={nodes.Cube039.geometry} material={materials['Rubber.001']} rotation={[Math.PI / 2, 0, 0]} scale={1000} />
        <mesh geometry={nodes.Cube041.geometry} material={materials['Material.056']} rotation={[Math.PI / 2, 0, 0]} scale={1000} />
        <mesh geometry={nodes.Cube042.geometry} material={materials['Material.056']} rotation={[Math.PI / 2, 0, 0]} scale={1000} />
        <mesh geometry={nodes.Cube043.geometry} material={materials['Material.041']} rotation={[Math.PI / 2, 0, 0]} scale={1000} />
        <mesh geometry={nodes.Cube048.geometry} material={materials['Steel.004']} rotation={[Math.PI / 2, 0, 0]} scale={1000} />
        <mesh geometry={nodes.Cube049.geometry} material={materials['Steel.004']} rotation={[Math.PI / 2, 0, 0]} scale={1000} />
        <mesh geometry={nodes.Cube050.geometry} material={materials['Black plastic PL.004']} rotation={[Math.PI / 2, 0, 0]} scale={1000} />
        <mesh geometry={nodes.Cube054.geometry} material={materials['Dark Steel.002']} rotation={[Math.PI / 2, 0, 0]} scale={1000} />
        <mesh geometry={nodes.Cube055.geometry} material={materials['Dark Steel.002']} rotation={[Math.PI / 2, 0, 0]} scale={1000} />
        <mesh geometry={nodes.Cube056.geometry} material={materials['Material.045']} rotation={[Math.PI / 2, 0, 0]} scale={1000} />
        <mesh geometry={nodes.Cube059.geometry} material={materials['Steel.004']} rotation={[Math.PI / 2, 0, 0]} scale={1000} />
        <mesh geometry={nodes.Cube060.geometry} material={materials['Steel.004']} rotation={[Math.PI / 2, 0, 0]} scale={1000} />
        <mesh geometry={nodes.Cube062.geometry} material={materials['Rubber.001']} rotation={[Math.PI / 2, 0, 0]} scale={1000} />
        <mesh geometry={nodes.Cube063.geometry} material={materials['Rubber.001']} rotation={[Math.PI / 2, 0, 0]} scale={1000} />
        <mesh geometry={nodes.Cube069.geometry} material={materials['Rubber.001']} rotation={[Math.PI / 2, 0, 0]} scale={1000} />
        <mesh geometry={nodes.Cube072.geometry} material={materials['Black Plastic.001']} rotation={[Math.PI / 2, 0, 0]} scale={1000} />
        <mesh geometry={nodes.Cube076.geometry} material={materials['Matte Black.001']} rotation={[Math.PI / 2, 0, 0]} scale={1000} />
        <mesh geometry={nodes.Cube078.geometry} material={materials['Black Plastic.001']} rotation={[Math.PI / 2, 0, 0]} scale={1000} />
        <mesh geometry={nodes.Cube080.geometry} material={materials['Black Plastic.001']} rotation={[Math.PI / 2, 0, 0]} scale={1000} />
        <mesh geometry={nodes.Cube084.geometry} material={materials['Material.041']} rotation={[Math.PI / 2, 0, 0]} scale={1000} />
        <mesh geometry={nodes.Cube086.geometry} material={materials['Steel.005']} rotation={[Math.PI / 2, 0, 0]} scale={1000} />
        <mesh geometry={nodes.Cube087.geometry} material={materials['Steel.005']} rotation={[Math.PI / 2, 0, 0]} scale={1000} />
        <mesh geometry={nodes.Cube088.geometry} material={materials['Steel.004']} rotation={[Math.PI / 2, 0, 0]} scale={1000} />
        <mesh geometry={nodes.Cube089.geometry} material={materials['Material.040']} rotation={[Math.PI / 2, 0, 0]} scale={1000} />
        <mesh geometry={nodes.Cube090.geometry} material={materials['Dark Steel.002']} rotation={[Math.PI / 2, 0, 0]} scale={1000} />
        <mesh geometry={nodes.Cylinder.geometry} material={materials['cart white.002']} rotation={[Math.PI / 2, 0, 0]} scale={1000} />
        <mesh geometry={nodes.Cylinder001.geometry} material={materials['Ocean Tropic']} rotation={[Math.PI / 2, 0, 0]} scale={1000} />
        <mesh geometry={nodes.Cylinder002.geometry} material={materials['Black Plastic.001']} rotation={[Math.PI / 2, 0, 0]} scale={1000} />
        <mesh geometry={nodes.Cylinder003.geometry} material={materials['cart white.002']} rotation={[Math.PI / 2, 0, 0]} scale={1000} />
        <mesh geometry={nodes.Cylinder004.geometry} material={materials.Alexa} rotation={[Math.PI / 2, 0, 0]} scale={1000} />
        <mesh geometry={nodes.Cylinder006.geometry} material={materials['Pure Passion']} rotation={[Math.PI / 2, 0, 0]} scale={1000} />
        <mesh geometry={nodes.Cylinder007.geometry} material={materials['Material.057']} rotation={[Math.PI / 2, 0, 0]} scale={1000} />
        <mesh geometry={nodes.Cylinder009.geometry} material={materials['Material.058']} rotation={[Math.PI / 2, 0, 0]} scale={1000} />
        <mesh geometry={nodes.Cylinder010.geometry} material={materials['Material.060']} rotation={[Math.PI / 2, 0, 0]} scale={1000} />
        <mesh geometry={nodes.Cylinder012.geometry} material={materials['Glossy Tint']} rotation={[Math.PI / 2, 0, 0]} scale={1000} />
        <mesh geometry={nodes.Cylinder013.geometry} material={materials['Stainless Steel.001']} rotation={[Math.PI / 2, 0, 0]} scale={1000} />
        <mesh geometry={nodes.Cylinder016.geometry} material={materials['Black plastic PL.007']} rotation={[Math.PI / 2, 0, 0]} scale={1000} />
        <mesh geometry={nodes.Cylinder019.geometry} material={materials.Afternoon} rotation={[Math.PI / 2, 0, 0]} scale={1000} />
        <mesh geometry={nodes.Cylinder020.geometry} material={materials.Havana} rotation={[Math.PI / 2, 0, 0]} scale={1000} />
        <mesh geometry={nodes.Cylinder021.geometry} material={materials['Stainless Steel.001']} rotation={[Math.PI / 2, 0, 0]} scale={1000} />
        <mesh geometry={nodes.Cylinder022.geometry} material={materials['Stainless Steel.001']} rotation={[Math.PI / 2, 0, 0]} scale={1000} />
        <mesh geometry={nodes.Cylinder031.geometry} material={materials['Stainless Steel.001']} rotation={[Math.PI / 2, 0, 0]} scale={1000} />
        <mesh geometry={nodes.Cylinder040.geometry} material={materials['Dark Steel.002']} rotation={[Math.PI / 2, 0, 0]} scale={1000} />
        <mesh geometry={nodes.Cylinder041.geometry} material={materials['Dark Steel.002']} rotation={[Math.PI / 2, 0, 0]} scale={1000} />
        <mesh geometry={nodes.Cylinder043.geometry} material={materials['Rough Iron Steel.001']} rotation={[Math.PI / 2, 0, 0]} scale={1000} />
        <mesh geometry={nodes.Mesh.geometry} material={materials['Material.036']} rotation={[Math.PI / 2, 0, 0]} scale={1000} />
        <mesh geometry={nodes.Mesh001.geometry} material={materials['BASE.001']} rotation={[Math.PI / 2, 0, 0]} scale={1000} />
        <mesh geometry={nodes.Mesh002.geometry} material={materials['Black plastic PL.004']} rotation={[Math.PI / 2, 0, 0]} scale={1000} />
        <mesh geometry={nodes.Mesh003.geometry} material={materials['Black plastic PL.004']} rotation={[Math.PI / 2, 0, 0]} scale={1000} />
        <mesh geometry={nodes.Mesh004.geometry} material={materials['Black plastic PL.005']} rotation={[Math.PI / 2, 0, 0]} scale={1000} />
        <mesh geometry={nodes.Mesh005.geometry} material={materials['Matte Black.001']} rotation={[Math.PI / 2, 0, 0]} scale={1000} />
        <mesh geometry={nodes.Mesh006.geometry} material={materials['Matte Black.001']} rotation={[Math.PI / 2, 0, 0]} scale={1000} />
        <mesh geometry={nodes.Mesh011.geometry} material={materials['Material.049']} rotation={[Math.PI / 2, 0, 0]} scale={1000} />
        <mesh geometry={nodes.Mesh012.geometry} material={materials['Material.049']} rotation={[Math.PI / 2, 0, 0]} scale={1000} />
        <mesh geometry={nodes.Mesh019.geometry} material={materials['Material.019']} rotation={[Math.PI / 2, 0, 0]} scale={1000} />
        <mesh geometry={nodes.Mesh020.geometry} material={materials['Material.019']} rotation={[Math.PI / 2, 0, 0]} scale={1000} />
        <mesh geometry={nodes.Mesh022.geometry} material={materials['rubber.001']} rotation={[Math.PI / 2, 0, 0]} scale={1000} />
        <mesh geometry={nodes.Mesh023.geometry} material={materials['Material.053']} rotation={[Math.PI / 2, 0, 0]} scale={1000} />
        <mesh geometry={nodes.Mesh030.geometry} material={materials['Material.061']} rotation={[Math.PI / 2, 0, 0]} scale={1000} />
        <mesh geometry={nodes.Mesh031.geometry} material={materials['rubber.001']} rotation={[Math.PI / 2, 0, 0]} scale={1000} />
        <mesh geometry={nodes.Plane.geometry} material={materials['Material.048']} rotation={[Math.PI / 2, 0, 0]} scale={1000} />
        <mesh geometry={nodes.Plane001.geometry} material={materials['Black plastic PL.004']} rotation={[Math.PI / 2, 0, 0]} scale={1000} />
        <mesh geometry={nodes.Plane002.geometry} material={materials['Steel.003']} rotation={[Math.PI / 2, 0, 0]} scale={1000} />
        <mesh geometry={nodes.Plane003.geometry} material={materials['Dark Steel.003']} rotation={[Math.PI / 2, 0, 0]} scale={1000} />
        <mesh geometry={nodes.Plane004.geometry} material={materials['Black plastic PL.006']} rotation={[Math.PI / 2, 0, 0]} scale={1000} />
        <mesh geometry={nodes.Plane006.geometry} material={materials['Black 1.002']} rotation={[Math.PI / 2, 0, 0]} scale={1000} />
        <mesh geometry={nodes.Plane010.geometry} material={materials['metal.001']} rotation={[Math.PI / 2, 0, 0]} scale={1000} />
        <mesh geometry={nodes.Plane013.geometry} material={materials['Material.046']} rotation={[Math.PI / 2, 0, 0]} scale={1000} />
        <mesh geometry={nodes.Plane014.geometry} material={materials['Material.038']} rotation={[Math.PI / 2, 0, 0]} scale={1000} />
        <mesh geometry={nodes.Plane015.geometry} material={materials['Black plastic old scratched.001']} rotation={[Math.PI / 2, 0, 0]} scale={1000} />
        <mesh geometry={nodes.Plane016.geometry} material={materials['Black.001']} rotation={[Math.PI / 2, 0, 0]} scale={1000} />
        <mesh geometry={nodes.Plane018.geometry} material={materials['Material.017']} rotation={[Math.PI / 2, 0, 0]} scale={1000} />
        <mesh geometry={nodes.Plane019.geometry} material={materials['Material.039']} rotation={[Math.PI / 2, 0, 0]} scale={1000} />
        <mesh geometry={nodes.Plane021.geometry} material={materials['Material.047']} rotation={[Math.PI / 2, 0, 0]} scale={1000} />
        <mesh geometry={nodes.Plane022.geometry} material={materials['Steel.005']} rotation={[Math.PI / 2, 0, 0]} scale={1000} />
        <mesh geometry={nodes.Plane025.geometry} material={materials['Dark Steel.002']} rotation={[Math.PI / 2, 0, 0]} scale={1000} />
        <mesh geometry={nodes.Plane026.geometry} material={materials['Steel.004']} rotation={[Math.PI / 2, 0, 0]} scale={1000} />
        <mesh geometry={nodes.Plane029.geometry} material={materials['cart white.002']} rotation={[Math.PI / 2, 0, 0]} scale={1000} />
        <mesh geometry={nodes.Plane030.geometry} material={materials['Material.038']} rotation={[Math.PI / 2, 0, 0]} scale={1000} />
        <mesh geometry={nodes.Plane031.geometry} material={materials['Material.052']} rotation={[Math.PI / 2, 0, 0]} scale={1000} />
        <mesh geometry={nodes.Plane032.geometry} material={materials['Material.038']} rotation={[Math.PI / 2, 0, 0]} scale={1000} />
        <mesh geometry={nodes.Plane033.geometry} material={materials['Tarp Sports Cherry Red Black Topstitch.002']} rotation={[Math.PI / 2, 0, 0]} scale={1000} />
        <mesh geometry={nodes.Plane034.geometry} material={materials['Tarp Sports Cherry Red Black Topstitch.002']} rotation={[Math.PI / 2, 0, 0]} scale={1000} />
        <mesh geometry={nodes.Plane035.geometry} material={materials['Dark_metal.001']} rotation={[Math.PI / 2, 0, 0]} scale={1000} />
        <mesh geometry={nodes.Plane036.geometry} material={materials['Dark_metal.001']} rotation={[Math.PI / 2, 0, 0]} scale={1000} />
        <mesh geometry={nodes.Plane037.geometry} material={materials['Dark_metal.001']} rotation={[Math.PI / 2, 0, 0]} scale={1000} />
        <mesh geometry={nodes.Plane038.geometry} material={materials['Dark_metal.001']} rotation={[Math.PI / 2, 0, 0]} scale={1000} />
        <mesh geometry={nodes.Plane039.geometry} material={materials['Dark_metal.001']} rotation={[Math.PI / 2, 0, 0]} scale={1000} />
        <mesh geometry={nodes.Plane040.geometry} material={materials['rubber.001']} rotation={[Math.PI / 2, 0, 0]} scale={1000} />
        <mesh geometry={nodes.Plane041.geometry} material={materials['Dark_metal.001']} rotation={[Math.PI / 2, 0, 0]} scale={1000} />
        <mesh geometry={nodes.Plane042.geometry} material={materials['Glass.002']} rotation={[Math.PI / 2, 0, 0]} scale={1000} />
        <mesh geometry={nodes.Plane044.geometry} material={materials['Black plastic PL.004']} rotation={[Math.PI / 2, 0, 0]} scale={1000} />
        <mesh geometry={nodes.Plane045.geometry} material={materials['cart white.003']} rotation={[Math.PI / 2, 0, 0]} scale={1000} />
        <mesh geometry={nodes.Plane047.geometry} material={materials['rubber.001']} rotation={[Math.PI / 2, 0, 0]} scale={1000} />
        <mesh geometry={nodes.Plane048.geometry} material={materials['rubber.001']} rotation={[Math.PI / 2, 0, 0]} scale={1000} />
        <mesh geometry={nodes.Plane050.geometry} material={materials['Material.038']} rotation={[Math.PI / 2, 0, 0]} scale={1000} />
        <mesh geometry={nodes.Plane054.geometry} material={materials['Material.037']} rotation={[Math.PI / 2, 0, 0]} scale={1000} />
        <mesh geometry={nodes.Plane070.geometry} material={materials['Glass.002']} rotation={[Math.PI / 2, 0, 0]} scale={1000} />
        <mesh geometry={nodes['WhatsApp_Image_2023-03-19_at_11711_AM_(1)001'].geometry} material={materials['Material.035']} rotation={[Math.PI / 2, 0, 0]} scale={1000} />
        <mesh geometry={nodes['WhatsApp_Image_2023-03-19_at_11711_AM_(1)004'].geometry} material={materials['Material.035']} rotation={[Math.PI / 2, 0, 0]} scale={1000} />
        <mesh geometry={nodes['WhatsApp_Image_2023-05-06_at_95846_AM_copy'].geometry} material={materials['WhatsApp Image 2023-05-06 at 9.58.46 AM copy.001']} rotation={[Math.PI / 2, 0, 0]} scale={1000} />
        <mesh geometry={nodes['WhatsApp_Image_2023-05-06_at_95846_AM_copy001'].geometry} material={materials['WhatsApp Image 2023-05-06 at 9.58.46 AM copy.001']} rotation={[Math.PI / 2, 0, 0]} scale={1000} />
      </group>
      <mesh geometry={nodes.Object_0_1.geometry} material={materials.shed} />
      <mesh geometry={nodes.Object_0_2.geometry} material={materials.Concrete_Wall_vhjldck} />
    </group>
  )
}

useGLTF.preload('/models/Six_Seater_Kart.glb')
