/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.11 ./public/models/others/Solar Panel.glb --t
*/

import * as THREE from 'three'
import React, { useRef } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    Plane052: THREE.Mesh
    Plane062: THREE.Mesh
    Plane062_1: THREE.Mesh
    Plane062_2: THREE.Mesh
  }
  materials: {
    ['Dark Steel.002']: THREE.MeshStandardMaterial
    frame_03: THREE.MeshStandardMaterial
    ['solar.03']: THREE.MeshStandardMaterial
    ['plastic.03']: THREE.MeshStandardMaterial
  }
}

type ActionName = '150W_variant_02' | 'Plane.052'
type GLTFActions = Record<ActionName, THREE.AnimationAction>

export function SolarPanelModel(props: JSX.IntrinsicElements['group']) {
  const group = useRef<THREE.Group>()
  const { nodes, materials, animations } = useGLTF('/models/others/Solar Panel.glb') as GLTFResult
  const { actions } = useAnimations<GLTFActions>(animations, group)
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <mesh name="Plane052" geometry={nodes.Plane052.geometry} material={materials['Dark Steel.002']} position={[0.02, 3.15, 0.25]} scale={[0.86, 1.06, 1.58]} />
        <group name="150W_variant_02" position={[0.02, 3.14, 0.25]} scale={[2.5, 1, 2.2]}>
          <mesh name="Plane062" geometry={nodes.Plane062.geometry} material={materials.frame_03} />
          <mesh name="Plane062_1" geometry={nodes.Plane062_1.geometry} material={materials['solar.03']} />
          <mesh name="Plane062_2" geometry={nodes.Plane062_2.geometry} material={materials['plastic.03']} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/models/others/Solar Panel.glb')
