/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.3 SP6.glb --t
*/

import * as THREE from 'three'
import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    Plane068: THREE.Mesh
    Plane068_1: THREE.Mesh
    Plane068_2: THREE.Mesh
    Plane068_3: THREE.Mesh
  }
  materials: {
    ['Dark Steel.002']: THREE.MeshStandardMaterial
    frame_03: THREE.MeshStandardMaterial
    ['solar.03']: THREE.MeshStandardMaterial
    ['plastic.03']: THREE.MeshStandardMaterial
  }
}

export function KartSixSolarPanelModel(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/models/others/SP6.glb') as GLTFResult
  return (
    <group {...props} dispose={null}>
      <group position={[0.018, 3.161, 0.253]} scale={[0.806, 0.931, 1.578]}>
        <mesh geometry={nodes.Plane068.geometry} material={materials['Dark Steel.002']} />
        <mesh geometry={nodes.Plane068_1.geometry} material={materials.frame_03} />
        <mesh geometry={nodes.Plane068_2.geometry} material={materials['solar.03']} />
        <mesh geometry={nodes.Plane068_3.geometry} material={materials['plastic.03']} />
      </group>
    </group>
  )
}

useGLTF.preload('/models/others/SP6.glb')
