/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.11 ./public/models/steerings/Steering 2.glb --t
*/

import * as THREE from 'three'
import React, { useRef } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    Plane056: THREE.Mesh
    Plane057: THREE.Mesh
  }
  materials: {
    ['Black.003']: THREE.MeshStandardMaterial
    ['Steel.002']: THREE.MeshStandardMaterial
  }
}

type ActionName = 'Plane.056' | 'Plane.057'
type GLTFActions = Record<ActionName, THREE.AnimationAction>

export function SteeringModel2(props: JSX.IntrinsicElements['group']) {
  const group = useRef<THREE.Group>(null)
  const { nodes, materials, animations } = useGLTF('/models/steerings/Steering 2.glb') as GLTFResult
  const { actions } = useAnimations<any>(animations, group)
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <mesh name="Plane056" geometry={nodes.Plane056.geometry} material={materials['Black.003']} position={[-0.57, 2.02, -1.49]} rotation={[0.78, 0, 0]} scale={0.09} />
        <mesh name="Plane057" geometry={nodes.Plane057.geometry} material={materials['Steel.002']} position={[-0.57, 2.02, -1.49]} rotation={[0.78, 0, 0]} scale={0.09} />
      </group>
    </group>
  )
}

useGLTF.preload('/models/steerings/Steering 2.glb')
