/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.11 ./public/models/steerings/Steering 3.glb --t
*/

import * as THREE from 'three'
import React, { useRef } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    Mesh001: THREE.Mesh
    Mesh001_1: THREE.Mesh
    Mesh001_2: THREE.Mesh
  }
  materials: {
    ['Dark Steel.003']: THREE.MeshStandardMaterial
    ['Black.003']: THREE.MeshStandardMaterial
    ['Rubber 00']: THREE.MeshStandardMaterial
  }
}

type ActionName = 'steer.001'
type GLTFActions = Record<ActionName, THREE.AnimationAction>

export function SteeringModel3(props: JSX.IntrinsicElements['group']) {
  const group = useRef<THREE.Group>(null)
  const { nodes, materials, animations } = useGLTF('/models/steerings/Steering 3.glb') as GLTFResult
  const { actions } = useAnimations<any>(animations, group)
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group name="steer001" position={[-0.55, 1.8, -2.22]} rotation={[0.44, -1.57, -0.87]} scale={[0.89, 1.47, 0.89]}>
          <mesh name="Mesh001" geometry={nodes.Mesh001.geometry} material={materials['Dark Steel.003']} />
          <mesh name="Mesh001_1" geometry={nodes.Mesh001_1.geometry} material={materials['Black.003']} />
          <mesh name="Mesh001_2" geometry={nodes.Mesh001_2.geometry} material={materials['Rubber 00']} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/models/steerings/Steering 3.glb')
