/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.5 public/models/steerings/Steering 4.glb --t
*/

import * as THREE from 'three'
import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    Torus002_1: THREE.Mesh
    Torus002_2: THREE.Mesh
  }
  materials: {
    ['Black plastic old scratched.002']: THREE.MeshStandardMaterial
    ['Material.003']: THREE.MeshStandardMaterial
  }
}

export function SteeringModel4(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/models/steerings/Steering 4.glb') as GLTFResult
  return (
    <group {...props} dispose={null}>
      <group position={[-0.562, 1.988, -1.47]} rotation={[0.743, -0.481, 0.022]} scale={0.105}>
        <mesh geometry={nodes.Torus002_1.geometry} material={materials['Black plastic old scratched.002']} />
        <mesh geometry={nodes.Torus002_2.geometry} material={materials['Material.003']} />
      </group>
    </group>
  )
}

useGLTF.preload('/models/steerings/Steering 4.glb')
