/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.11 ./public/models/steerings/Steering 1.glb --t
*/

import * as THREE from 'three'
import React, { useRef } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    Plane034: THREE.Mesh
    Plane049: THREE.Mesh
    Plane049_1: THREE.Mesh
  }
  materials: {
    Black: THREE.MeshStandardMaterial
    ['Material.017']: THREE.MeshStandardMaterial
    ['Material.019']: THREE.MeshStandardMaterial
  }
}

type ActionName = 'Plane.034' | 'Plane.033'
type GLTFActions = Record<ActionName, THREE.AnimationAction>

export function SteeringModel1(props: JSX.IntrinsicElements['group']) {
  const group = useRef<THREE.Group>(null)
  const { nodes, materials, animations } = useGLTF('/models/steerings/Steering 1.glb') as GLTFResult
  const { actions } = useAnimations<any>(animations, group)
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <mesh name="Plane034" geometry={nodes.Plane034.geometry} material={materials.Black} position={[-0.56, 2.02, -1.5]} rotation={[0.78, 0, 0]} scale={0.09} />
        <group name="Plane033" position={[-0.53, 2.14, -1.31]}>
          <mesh name="Plane049" geometry={nodes.Plane049.geometry} material={materials['Material.017']} />
          <mesh name="Plane049_1" geometry={nodes.Plane049_1.geometry} material={materials['Material.019']} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/models/steerings/Steering 1.glb')
